### ISSUE TITLE
Proxy pane missing Exit (x) button [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#10]
**Describe the bug**
Proxy pane missing exit button.

**To Reproduce/Line of code causing issue**
Open proxy pane

**Expected behaviour**
Be able to exit without ragequitting the client

**Screenshots**
![image](https://user-images.githubusercontent.com/64224090/184694688-6fdf5e5d-c2ab-4b37-824d-d57116ea545d.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator:  Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by constt** [comment]
This has been resolved
