### ISSUE TITLE
[BUG] Issue with objects in Molch

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#100]
**Describe the bug**
Many of the objects that serve as art / landscape are being picked up as Doors or Stairs rather than the appropriate object, when using the Interactive Objects debug.  These objects aren't really interactive either, but I'm not sure how that is determined.

**To Reproduce/Line of code causing issue**
1. Go to Molch
2. Here is a debug when interacting with a "Stairs" that is not really "Stairs":
[Object Handler] Interacting with (Stairs) at tile (1294, 3654, 0) with options: [Climb-up] SUCCESS

**Screenshots**
Here is the interactive objects debug from the stairs in question above:
https://gyazo.com/a663d71481b6537202fd8a30902c7a51

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by constt** [comment]
@5Henveru2 should be fixed

**Comment by iDznPB** [comment]
@5Henveru2 any update?

**Comment by 5Henveru2** [comment]
Yes, this is resolved.
