### ISSUE TITLE
[BUG]NPC names (pollniveach/crewmembers at docks) are null

### ISSUE THREAD

**Issue by Nickert1337** [powbot/issues#101]
**Describe the bug**
NPCs in this area have null as name

**To Reproduce/Line of code causing issue**
1. Go to pollniveach, enable NPCs debug

**Expected behavior**
Bandit name shown

**Screenshots**
![image](https://user-images.githubusercontent.com/98966743/191464661-f3d11251-8c34-4035-b5a0-3527a892762f.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: [Bluestacks]
 - OS: [Android Pie]
 - Arch: [ARM64]

**Comment by iDznPB** [comment]
to add to this (was just raising it when I saw this one come through)
![image](https://user-images.githubusercontent.com/34009165/191464843-ca057939-c7ad-4e09-9eb0-afc6723aabf8.png)
the Trader Crewmember at the docks are also null

**Comment by constt** [comment]
@iDznPB @Nickert1337 should be fixed
