### ISSUE TITLE
[BUG]Action menu item does not exist

### ISSUE THREAD

**Issue by Nickert1337** [powbot/issues#102]
**Describe the bug**
When trying to interact with a bandit the logs say that the interaction failed and the click did indeed get cancelled.

**To Reproduce/Line of code causing issue**
```
Npc bandit = getBandit();
bandit.interact("Knock-Out");
```

**Expected behavior**
The bot should be clicking 'Knock-Out'.

**Logs**
```[INFO] Got TouchEvent(type=Press, mod=0, x=309, y=150, isScriptInput=true, consumed=false, unscaled=Point(x=553, y=268)) (73
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=309, y=150, isScriptInput=true, consumed=false, unscaled=Point(x=553, y=268))
[INFO] Got TouchEvent(type=Release, mod=0, x=309, y=150, isScriptInput=true, consumed=false, unscaled=Point(x=553, y=268)) (73
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=309, y=150, isScriptInput=true, consumed=false, unscaled=Point(x=553, y=268))
[INFO] trying to click menu itemorg.powbot.api.rt4.Menu$TextFilter@cd21eea
[SEVERE] Menu item doesn't exist - [Attack Menaphite Thug  (level-55), Talk-to Menaphite Thug  (level-55), Pickpocket Menaphite Thug  (level-55), Lure Menaphite Thug  (level-55), Knock-Out Menaphite Thug  (level-55), Walk here, Examine Menaphite Thug  (level-55), Cancel]
```

![image](https://user-images.githubusercontent.com/98966743/191467782-ff8208d8-62b0-45fa-8bb3-842c7f3b5378.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: [Bluestacks]
 - OS: [Android Pie]
 - Arch: [ARM64]

**Comment by constt** [comment]
@Nickert1337 does the thugs name show on npc debug

**Comment by Nickert1337** [comment]
Their name is 'null' as described in [https://github.com/powbot/issues/issues/101](url)

**Comment by Nickert1337** [comment]
Seems to work now. I'll close it.
