### ISSUE TITLE
[BUG]Component.name() produces nill

### ISSUE THREAD

**Issue by Nickert1337** [powbot/issues#103]
**Describe the bug**
When quering the name of a open interface it shows the name in the widget explorer but in code it produces a nill.

**To Reproduce/Line of code causing issue**
```
System.out.println("Direct: " + Widgets.widget(242).component(3).component(0).name());
```
Produces
```
[] Direct: 
```

With the widget open. If you use the widget explorer to check the widget it shows the name in the debug.

![image](https://user-images.githubusercontent.com/98966743/191508331-73aa58d4-3cdb-46f9-a6a8-c97bf8cfba8b.png)

**Expected behavior**
.name() should return servery dish in this case. (It used to do this pre-native; I didn't change my script)

**Emulator or device (please complete the following information):**
 - Device/Emulator: [Bluestacks]
 - OS: [Android Pie]
 - Arch: [ARM64]

**Comment by constt** [comment]
This has been fixed
