### ISSUE TITLE
[BUG] Game.tab() returns NONE erroneously

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#104]
**Describe the bug**
When you have the "Grouping" or the "Chat-channel" tabs open, which fall under the Clan Chat icon, Game.tab() returns NONE erroneously.  The "Ignore List" also comes up as NONE.

**To Reproduce/Line of code causing issue**
1. Open the Grouping tab
2. Enable the "Client State" debug
3. Check the listed tab as NONE

**Expected behavior**
The "Grouping" and "Chat-channel" tabs should return CLAN_CHAT as their tab.  The "Ignore List" should return FRIENDS_LIST.
OR
There should be separate enum values for the alternate tab configs.

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch:ARM64

**Comment by constt** [comment]
Resoolved in next build

**Comment by 5Henveru2** [comment]
This is still broken.  When the client has the GROUPING tab picked among the CLAN_CHAT tab icons, the client recognizes that it is open, but the function Game.tab(Game.Tab.GROUPING) fails.  Really, the best solution is the first one I mentioned above: to consider the alternative tabs as the same tab and to open them via the CLAN_CHAT tab.  This would also need to be done for the IGNORE_LIST, but that one isn't as important.  Grouping is used for Minigames teleports which are very useful for my webwalker.  In the current state, the client cannot open the appropriate tab via Game.tab methods while the Grouping icon is selected, so it has to be done via widgets.
