### ISSUE TITLE
[BUG] Skills.level()/realLevel() returning -1

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#105]
**To Reproduce/Line of code causing issue**
Both methods are returning -1
```
		System.out.println("RC: "+Skills.realLevel(Skill.Runecrafting.getIndex()));
		System.out.println("HP: "+Skills.level(Constants.SKILLS_HITPOINTS));
```

**Expected behavior**
Returning the actual levels

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB Are you trying to read this right after login?

**Comment by iDznPB** [comment]
mm I was in the game for some time but had to restart because inventory was bugged/null, looks like that's fixed the issue

**Comment by iDznPB** [comment]
Reopening this as while it's not all the time, it's sporadic but definitely happening. Seen it happen in my scripts and seen reports of people spam eating food because health is returning -1

**Comment by constt** [comment]
@iDznPB What's client state when it's -1

**Comment by iDznPB** [comment]
I ran for over an hour today without it reaching my failsafe code, not sure if there's been any changes recently that could effect it?
@constt

**Comment by constt** [comment]
> I ran for over an hour today without it reaching my failsafe code, not sure if there's been any changes recently that could effect it? @constt

Yeah I did tweak it

**Comment by iDznPB** [comment]
> > I ran for over an hour today without it reaching my failsafe code, not sure if there's been any changes recently that could effect it? @constt
> 
> Yeah I did tweak it

Cool, did 2 1 hour+ sessions and didn't see it hit -1 so will close, thanks!
