### ISSUE TITLE
[BUG] Inventory not updating correctly

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#106]
**Describe the bug**
When the inventory isn't open, it doesn't update correctly. While it's easy enough to say "Open the inventory when you want to use it" it's not as simple as that. for example here in the clip below, the magic tab needs to be open to cast the spell, and opening the inventory makes absolutely no sense.

EDIT: Also now seeing reports of inventory items just straight up returning null or empty when they're not
https://discord.com/channels/341014842745815054/1014245351307358308/1024488427363770378

**Expected behavior**
Update the inventory stream while inventory is not open.

**Screenshots**
https://i.imgur.com/Q6yMQ9o.mp4

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB just pushed a change to improve Inventory#opened and add more info to the inventory debug if you could test and report back pls

**Comment by iDznPB** [comment]
https://imgur.com/a/o9PTN7M
Still not updating

**Comment by iDznPB** [comment]
Can confirm working <3
