### ISSUE TITLE
[BUG] Bank.present() or Bank.nearest().tile().distanceTo() slow to return

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#108]
**Describe the bug**
Checking bank.present() or Bank.nearest().tile().distanceTo(Players.local())
when there's not one loaded, takes over a second to return. Since banking tasks will need to validate a bank in order to run, this code gets called alot and in turn causes 1s breaks all over the palce.

**To Reproduce/Line of code causing issue**

```
Bank.present()
Bank.nearest().tile().distanceTo(Players.local())
```

**Expected behavior**
Should be an extremely quick return as if there's no bank nearby

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB made it faster could you test

**Comment by iDznPB** [comment]
@constt sex on legs works perfectly thanks!
