### ISSUE TITLE
[BUG] Magic .cast() always returning false

### ISSUE THREAD

**Issue by Barcodeyboi** [powbot/issues#109]
**Describe the bug**
Magic related bug. 
.cast() casts a spell and should return true if it succesfully casted the spell. Currently it always returns false even when the cast was succesfull.

**To Reproduce/Line of code causing issue**
```
private val logger = Logger.getLogger(this.javaClass.name)
val result = Magic.ArceuusSpell.BASIC_REANIMATION.cast()
logger.info(result.toString())
```

**Expected behavior**
Return true if the spell was succesfully casted

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by constt** [comment]
@Barcodeyboi pushed fix plesse test in 20

**Comment by xpr0legendx** [comment]
Thanks @constt, issue is resolved!

**Comment by Barcodeyboi** [comment]
Thanks @constt, issue is resolved!
