### ISSUE TITLE
Selected Item debug does not report the selected item & causes crash if inv is not open [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#11]
**Describe the bug**
Item is selected in inventory, does not report it's values.

**To Reproduce/Line of code causing issue**
Select and item in inventory 

**Screenshots**
![image](https://user-images.githubusercontent.com/64224090/184857282-82682483-2a70-4701-906c-8db4fdfb45e5.png)

![image](https://user-images.githubusercontent.com/64224090/184857346-dbe15e8d-f8ba-477f-9da6-9f7e67c823d3.png)

**Comment by constt** [comment]
@Protoprize Resolved
