### ISSUE TITLE
[BUG] Bank.depositInventory() incorrectly returning false

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#110]
**Describe the bug**
As per title, successfully hits deposit inventory, inventory is now empty, Inventory.stream().isEmpty() is true, and also the widget interaction is also correct

[INFO] got all wanted touch events
[INFO] wait for touch succeeded
[INFO] Received expected action - WidgetActionEvent(widgetId=786474, interaction=Deposit inventory, name=, id=1)

**Expected behavior**
if received expected action, wait for inventory to be empty

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB applied a fix

**Comment by iDznPB** [comment]
> @iDznPB applied a fix

@constt I've restarted, cleared cache, re-installed, but it still returns false

**Comment by iDznPB** [comment]
Working again, thank you!
