### ISSUE TITLE
[BUG] whack missclicks

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#111]
**Describe the bug**
I started to notice missclicks while in motion, which I can understand some of them, but then I got sent this video.
2-3 minutes is wahck.

https://youtu.be/8peWi8cyASY?t=124

I cache the object, step to it, interact with it; however even when he gets the menu open, it's missclicking the menu.
User is @English/@Clarkeyy

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: P64
 - Arch: ARM

**Additional context**
When asked to increase his resources, he said it happens on both 2/2 and 4/4 cores/gb

**Comment by constt** [comment]
@iDznPB should be fixed

**Comment by iDznPB** [comment]
Will close this, looks to be hella lot better!
