### ISSUE TITLE
[BUG] LunarSpell.xyz.cancast() always false

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#112]
**Describe the bug**
as per the title spells on the lunar spellbook seem to be returning false

**To Reproduce/Line of code causing issue**
```
System.out.println("LUNAR SPELL.canCast(): "+Magic.LunarSpell.SUPERGLASS_MAKE.canCast());
```

**Expected behavior**
Return the correct value

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/193838832-110a078c-c572-4c9e-913b-c8423babfbf7.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB Are you using a staff? What staff and what runes does it provide?

**Comment by iDznPB** [comment]
@constt 
I just tried using canCast() with the following combinations
All runes in inventory - still returns false
Partial runes in inventory but with fire staff - still returns false
All runes in runepouch - still returns false

**Comment by constt** [comment]
@iDznPB what spell and what runes you have

**Comment by iDznPB** [comment]
> @iDznPB what spell and what runes you have

@constt I've just checked to see and it's working again, not sure what changed but will close. Thanks!
