### ISSUE TITLE
[BUG] Bank.open() doesn't open chest banks

### ISSUE THREAD

**Issue by Barcodeyboi** [powbot/issues#116]
**Describe the bug**
Client doesn't open chest banks, but moveToBank() works for chest banks.

**To Reproduce/Line of code causing issue**
```
if (Bank.inViewport()) {
            if (Bank.open()) {
                Condition.wait { Bank.opened() }
            }
        } else {
            Movement.moveToBank()
            Camera.turnTo(Bank.nearest().tile())
        }
```

**Expected behavior**
Bank.open() should be able to open chest banks

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by iDznPB** [comment]
which bank specifically? Tested at Ferox Enclave and it worked fine

**Comment by Barcodeyboi** [comment]
Wintertodt

**Comment by PTYB** [comment]
Fixed a general bank chests issue, please confirm if its fixed?

**Comment by iDznPB** [comment]
Bank.open() now works at wintertodt
