### ISSUE TITLE
[ENHANCEMENT] Widget Closers - Activity advisor - Store

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#117]
**Describe the bug**
Activity advisor panel gets opened by accident and then remains open
Similarly with the bond store

372.4
![image](https://user-images.githubusercontent.com/34009165/194696832-cd8c5ca0-3f27-49d0-a92b-096a8abaa15b.png)

65.1.13
![image](https://user-images.githubusercontent.com/34009165/194696870-b3c9e882-c5ef-4efc-9ab8-db57c76a53e8.png)

**Expected behavior**
Similar to the world map closer, one to close these widgets too.

**Comment by constt** [comment]
thanks @iDznPB added

**Comment by iDznPB** [comment]
Working nicely, thank you!
