### ISSUE TITLE
[BUG] Bank.nearest() unable to find this chest

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#118]
**Describe the bug**
Bank chest @ Tile(x=1675, y=3615, floor=0, localX=51, localY=47)

**Expected behavior**
Bank to be found and able to be used.

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/194697452-22ccea58-4790-46aa-9019-0ebcbef13db6.png)
![image](https://user-images.githubusercontent.com/34009165/194697487-c557679b-7b83-4e4a-8d83-977f027a00e7.png)

**Additional Context**
It may be something to do with house favour? I'm assuming you can't use the bank until you've got X favour with the relevant house or something

**Comment by 5Henveru2** [comment]
Bank chests at:
Castle Wars - GameObject[id=4483,name=Bank chest,type=INTERACTIVE,tile=Tile(x=2444, y=3083, floor=0, localX=60, localY=43)]

Farming Guild - GameObject[id=26711,name=Bank chest,type=INTERACTIVE,tile=Tile(x=1253, y=3742, floor=0, localX=53, localY=70)]

also seem to be affected.

**Comment by PTYB** [comment]
Should be fixed in beta, please confirm

**Comment by iDznPB** [comment]
@5Henveru2 my original bank chest is now working, are you able to check and confirm yours?

**Comment by 5Henveru2** [comment]
Yes they are all working now, thanks
