### ISSUE TITLE
Game Tick debug does not work [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#12]
**Describe the bug**
Game Tick debug does not work

**Expected behavior**
Last tick printed out + duration

**Screenshots**
![image](https://user-images.githubusercontent.com/64224090/184857709-09ffb8fc-5438-4338-8efe-9e6e5f2d2005.png)

**Comment by constt** [comment]
@Protoprize Resolved, please confirm and close

**Comment by ghost** [comment]
Fixed
