### ISSUE TITLE
[BUG] Items missing name and other info.

### ISSUE THREAD

**Issue by ghost** [powbot/issues#120]
**Describe the bug**
First noticed on equipment debug but seems to affect all items in the game, whether in inventory or equipment. Item ID is always there and is correct. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64224090/195333090-069e5e56-decd-4711-9ebd-59329fec103d.png)

**Logs**
Equipment.get()
```
[] id: 26858 - name: Hat of the eye (red)
[] id: 9765 - name: 
[] id: 11978 - name: 
[] id: 1269 - name: 
[] id: 26860 - name: 
[] id: 26862 - name: 
[] id: 11859 - name: Graceful gloves
[] id: 26856 - name: 

```

Print out of each slot using `Equipment.itemAt(Equipment.Slot.)`
```
[] CAPE id: 9765 - name: 
[] FEET id: 26856 - name: 
[] HEAD id: 26858 - name: Hat of the eye (red)
[] HANDS id: 11859 - name: Graceful gloves
[] LEGS id: 26862 - name: 
[] MAIN_HAND id: 1269 - name: 
[] NECK id: 11978 - name: 
[] OFF_HAND id: -1 - name: 
[] QUIVER id: -1 - name: 
[] RING id: -1 - name: 
[] TORSO id: 26860 - name: 
[] UNKNOWN_1 id: -1 - name: 
[] UNKNOWN_2 id: -1 - name: 
[] UNKNOWN_3 id: -1 - name: 
```

**Comment by DeveloperRyan** [comment]
https://i.imgur.com/yBazy9b.png
[] id: 1359- name: 
[] id: 9765 - name: 
[] id: 9765 - name: 
[] id: 9765 - name: 
[] id: 9765 - name: 
[] id: 9765 - name: 
[] id: 9765 - name: 
[] id: 9765 - name: 
[] id: 9765 - name:

**Comment by constt** [comment]
fixed in ext

**Comment by iDznPB** [comment]
resolved
