### ISSUE TITLE
[BUG] Inventory Cache Returning Wrong Values

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#122]
**Describe the bug**
Inventory open, shows correctly; 0 items in the inventory; close inventory and it shows the below.

**Expected behavior**
return an empty inventory

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/195530834-7bb159d6-a336-4af8-b708-c4c8c5a237ed.png)
https://gyazo.com/7850990750a3464a90c5d8c406a16341

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Additional context**
Only noticed after the update yesterday.

**Comment by constt** [comment]
@iDznPB I've been unable to reproduce, does it happen in certain locations?

**Comment by constt** [comment]
Able to reproduce but only with item ids which are way too high, can't get it reproducing with valid item ids like you

**Comment by iDznPB** [comment]
@constt it was happening with an empty inventory, I'll have another look today, might also be related to #123

**Comment by iDznPB** [comment]
checked on a completely fresh install/bluestacks and then got this
![image](https://user-images.githubusercontent.com/34009165/195790454-0c811a07-fe32-4312-a330-fb036e07bc98.png)
again, empty inventory

**Comment by constt** [comment]
@iDznPB fixed in 20mins

**Comment by iDznPB** [comment]
Can confirm working again!
