### ISSUE TITLE
[BUG] Phantom Equipment Items

### ISSUE THREAD

**Issue by Zibele** [powbot/issues#123]
**Describe the bug**
When you have an item equipped, additional random phantom items are added.

**To Reproduce/Line of code causing issue**
Equip an item.

**Expected behavior**
For the debugger to show only items I have equipped.

**Screenshots**
![fd57b6909814e5ce3d41305a240898b2](https://user-images.githubusercontent.com/33414379/195554527-b29dde80-2bb5-437d-89eb-c36d2e191d41.png)

https://gyazo.com/fd57b6909814e5ce3d41305a240898b2

**Emulator or device (please complete the following information):**
 - Device/Emulator: [e.g. Bluestacks]
 - OS: [Android Pie]
 - Arch: [e.g. ARM64]

**Additional context**

**Comment by iDznPB** [comment]
I think this might also be related to #122 since it looks like similar items

**Comment by constt** [comment]
@Zibele fixed in 20mins

**Comment by Zibele** [comment]
@constt tested it, seems fine. Thanks.
