### ISSUE TITLE
[BUG] Wonky Point Generation

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#124]
**Describe the bug**
Point generation is wonky af. Ignores the model, uses a boundary box and seems weighted to the corners/edges of said boundary box.

**Expected behavior**
Generate a point from inside the model, no human is going to actively attempt to click outside of the actual object model

**Screenshots**

**Logs**
![image](https://user-images.githubusercontent.com/34009165/195705384-0385b83b-0df9-4978-b3a5-51d79f26b1d9.png)
![image](https://user-images.githubusercontent.com/34009165/195705405-0a44a165-53a7-40eb-a2a5-2e97b9dbc0e5.png)
![image](https://user-images.githubusercontent.com/34009165/195705398-37d3cc47-4524-4657-a5a9-11d3ccd8213f.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Additional context**
Only started looking into this as still seeing random missclicks where it's almost got the object but missed it at the edge; this explains why.

**Comment by constt** [comment]
@iDznPB thanks for this.

The issue is in hull point generation, I'm not smart enough to work that out so I've disabled it for now.

Point generation will now use models directly by default which will be a bit faster and less intensive and prob more accurate.

**Comment by iDznPB** [comment]
@constt tbh id say model is better than hulls anyway since hull only really works for standard shapes, anything less standard like that tree gets messed up with the blank space, will test today the update!

**Comment by iDznPB** [comment]
Looking good!
