### ISSUE TITLE
[BUG] Npc.interacting returns player with blank name and -1 level

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#125]
**Describe the bug**
When calling Npc.interacting on a valid npc, the Actor that is returned is inaccurate.  It should be returning my player, however it is returning this:
Player(name='', combatLevel=-1)

**To Reproduce/Line of code causing issue**
Run this code in falador center in a world where players are killing Guards and observe the log
`Npcs.stream().name("Guard").filter(n -> n.interacting() != Actor.getNil()).forEach(n -> System.out.println(n.interacting()));`

**Expected behavior**
It should an Actor with valid information

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by constt** [comment]
@5Henveru2 this should be fixed on beta in 20

**Comment by 5Henveru2** [comment]
Resolved
