### ISSUE TITLE
[BUG] dd bug (interacting with players under each other)

### ISSUE THREAD

**Issue by jcollerns972** [powbot/issues#126]
**Describe the bug**
When my player logs in, and wants to interact (trade) with another player, if the target player is hidden below another player or more players (death dot), my player cannot interact with them. It tries to click at a different coordinate, and when testing how this coordinate is rendered, (see image below). As you can see user "little timid" is the character on top, and if I want to interact with anyone under them, these players are rendered elsewhere, and my player tries to interact with that location, which is not the location of the actual player.
![image](https://user-images.githubusercontent.com/114522108/195940006-8dbeab4b-0524-4afe-aea8-7807e1bce3c0.png)

**To Reproduce/Line of code causing issue**
1. Have 2+ accounts stood on top of each other in one world
2. Log in on the account you want to test with
3. try to run any interaction code on the player under out of the 2 accounts already logged in

OR

```
Player targetPlayer = Players.stream().name("whateverPlayerIsUnder").first();
targetPlayer.interact("Trade")
```

**Expected behavior**
trades the person under the player

**Screenshots**
![image](https://user-images.githubusercontent.com/114522108/195938339-be9533c5-9a18-48ba-888d-e3bf3b78a58e.png)
![image](https://user-images.githubusercontent.com/114522108/195938355-6f6407a0-63ff-4dba-b9e1-278af65d8261.png)

As you can see from the above image, when the target player "krokedgaymer" is under the other player, the player render teleports somewhere else (where they are not) the streamable has a video of it. 

https://streamable.com/p7w8i6
**Logs**
If applicable, add logs relating to the issue.

**Emulator or device (please complete the following information):**
 - Bluestacks
 - PI
 - ARM64

**Additional context**

**Comment by constt** [comment]
@jcollerns972 I pushed an improvement, pleaase test in 15mins

**Comment by jcollerns972** [comment]
> @jcollerns972 I pushed an improvement, pleaase test in 15mins

Still thinks the player under is elsewhere, if you can see in the streamable below, ive set the target player to "krokedgaymer", and written these 2 lines of code. 
` player.draw();`
`Rendering.drawPolygon(player.model()player.localX(),player.localY());`
https://streamable.com/3zcqun

If i try to interact with "krokedgaymer" when I first log in, it will try to click where the player is drawn as seen in the streamable and with player.draw(), which is not on the dd, only until the player has moved will it actually capture the correct location of the player.

**Comment by jcollerns972** [comment]
Also, on another note, idk if it's just me but interacting is broken.


[] can trade player: little timid
[] Trading: little timid

[] Player interactions are interactions: [Walk here, Follow, Trade with, Report]

[INFO] got all wanted touch events

[INFO] wait for touch succeeded

[INFO] trying to click menu itemorg.powbot.api.rt4.Menu$TextFilter@531a5cb

[SEVERE] Menu item doesn't exist - [Walk here little timid  (level-68), Follow little timid  (level-68), Trade with little timid  (level-68), Follow krokedgaymer  (level-73), Trade with krokedgaymer  (level-73), Cancel]

[INFO] trying to click menu itemorg.powbot.api.rt4.Menu$click$1@ca9a1a8

[INFO] found menu item at 5

[INFO] got all wanted touch events

[INFO] wait for touch succeeded

[WARNING] Received unexpected action while waiting for Trade - GameActionEvent(v0=-1, widgetId=-1, rawOp=1006, id=-1, interaction='Cancel', rawEntityName='', mouseX=-1, mouseY=-1) 

^ log


`                        if(player.valid() && player.inViewport())
                        {
                            System.out.println("Trading: " + player.getName());
                            System.out.println("Player interactions are interactions: " + player.actions());
                            player.interact("Trade");
                        }`

^ code
this is the log from me trying to trade another player

**Comment by jcollerns972** [comment]
https://streamable.com/nlwddk a video showing what happens

[] Trading: krokedgaymer
[] Player interactions are interactions: [Walk here, Follow, Trade with, Report]
[INFO] got all wanted touch events
[INFO] wait for touch succeeded
[WARNING] Received unexpected action while waiting for Trade with - GameActionEvent(v0=621, widgetId=132, rawOp=23, id=0, interaction='Walk here', rawEntityName='', mouseX=-1, mouseY=-1) 
[] can trade player: krokedgaymer
[] Trading: krokedgaymer
[] Player interactions are interactions: [Walk here, Follow, Trade with, Report]
[INFO] got all wanted touch events
[INFO] wait for touch succeeded
[] can trade player: krokedgaymer
[] Trading: krokedgaymer
[] Player interactions are interactions: [Walk here, Follow, Trade with, Report]
[INFO] got all wanted touch events
[INFO] wait for touch succeeded
[] can trade player: krokedgaymer
[] Trading: krokedgaymer
[] Player interactions are interactions: [Walk here, Follow, Trade with, Report]
[INFO] got all wanted touch events
[INFO] wait for touch succeeded
[WARNING] Received unexpected action while waiting for Trade with - GameActionEvent(v0=631, widgetId=306, rawOp=23, id=0, interaction='Walk here', rawEntityName='', mouseX=-1, mouseY=-1) 
[] can trade player: krokedgaymer
[] Trading: krokedgaymer
[] Player interactions are interactions: [Walk here, Follow, Trade with, Report]
[INFO] got all wanted touch events
[INFO] wait for touch succeeded
[INFO] trying to click menu itemorg.powbot.api.rt4.Menu$TextFilter@f06056e
[INFO] found menu item at 2
[INFO] got all wanted touch events
[INFO] wait for touch succeeded
[INFO] Received expected action - GameActionEvent(v0=49, widgetId=49, rawOp=2047, id=1493, interaction='Trade with', rawEntityName='<col=ffffff>krokedgaymer<col=c0ff00>  (level-73)', mouseX=-1, mouseY=-1)

**Comment by jcollerns972** [comment]
hey @constt have you had the chance to take a look? https://streamable.com/nlwddk - here is the video showing what the bug looks like

**Comment by jcollerns972** [comment]
Fixed in latest update 19/12/2022 <3
