### ISSUE TITLE
[BUG] Object stream hangs the client.

### ISSUE THREAD

**Issue by Zibele** [powbot/issues#127]
**Describe the bug**
I suspect that object streams, are freezing the client. For some objects it interacts in 30 seconds or so, whereas for other objects it will take 5+ minutes.  The reason why I suspect that its the stream and not the interaction, is because it will hang even if there is no interaction.

**To Reproduce/Line of code causing issue**

```
 public boolean openDoor() {
        GameObject altarDoor = Objects.stream().name("Large door").action("Open").first();
        return altarDoor.valid()
                && altarDoor.interact("Open");
    }
 public boolean isDoorClosed() {
        GameObject altarDoor = Objects.stream().name("Large door").action("Open").first();
        return altarDoor.valid();
    }
```

**Expected behavior**
For an interaction to happen within 30 seconds, and for client to not hang.

**Logs**
[dump.txt](https://github.com/powbot/issues/files/9792010/dump.txt)

**Emulator or device (please complete the following information):**
 - Device/Emulator: [e.g. Bluestacks]
 - OS: [Android Pie]
 - Arch: [e.g. ARM64]

**Comment by constt** [comment]
@Zibele Throw a #within call on your stream and perhaps a type of boundary?

This won't be fixed anytime soon as there's no simple way to do it given how many iterations have to be performed if you are searching the entire region.

**Comment by Zibele** [comment]
@constt Okay cool will try that.

**Comment by Zibele** [comment]
@constt yeah that resolved the issue. Still slow, but definitely much faster.
