### ISSUE TITLE
[BUG] Npc interactions can be very slow

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#128]
**Describe the bug**
Calling Npc.interact often takes minimum 800ms, sometimes as much as 3500ms to execute.  The duration varies based upon zoom level and likely other factors.  

**To Reproduce/Line of code causing issue**
Go to Ferox Enclave, near the bank.
Run this code:
```
            Npc banker = Npcs.stream().name("Banker").first();
            long curr = System.currentTimeMillis();
            banker.interact("Bank");
            System.out.println("Time to interact: " + (System.currentTimeMillis() - curr));
```
This results in around 2800-3500ms interaction times for me, with the camera mostly zoomed out.  With default zoom, it's 1500-2500ms interaction times.

**Expected behavior**
Can we see if it's possible to reduce the time to interact?  It's difficult/impossible to script efficient behaviors when interaction times are so lagged.

**Logs**

```
[INFO] trying to click menu itemorg.powbot.api.rt4.Menu$TextFilter@6a3200e
[INFO] found menu item at 1
[INFO] got all wanted touch events
[INFO] wait for touch succeeded
[INFO] Received expected action - NpcActionEvent(name=Banker, id=11945, level=-1, interaction=Bank)
[] Time to interact: 3177
```

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by Zibele** [comment]
I think this is tied, to my previous bug report, with object streams. You need to include boundaries, such as within(). It resolved my issues.

**Comment by iDznPB** [comment]
I'd be curious to see what's taking the most time, caching your npc or the interaction. Also if you get those logs from logcat it'll be time stamped to see which parts are taking the longest.

**Comment by constt** [comment]
Found the bottleneck was in model point generation, have optimized it a bit.

Please test now

**Comment by 5Henveru2** [comment]
> I'd be curious to see what's taking the most time, caching your npc or the interaction. Also if you get those logs from logcat it'll be time stamped to see which parts are taking the longest.

As you can see from the code, it finds the npc before it it caches the time, so the time displayed was purely for the interact function.  It isn't related to looking up NPCs.


> Found the bottleneck was in model point generation, have optimized it a bit.
> 
> Please test now

I just tried stable and dev and had relatively similar results to before, but it's hard to say if it's changed.  I had some that were 4000ms, some that were 1200ms, but most around the 2400ms.

```
10-16 18:38:39.946 12855 12891 I System.out: Point(x=374, y=328)
10-16 18:38:39.950 12855 12891 E PowBotNative: ProcessInputEvent(134217728, 0x7609d7052500)
10-16 18:38:39.950 12855 12891 I System.out: event at 402.0 352.0 Point(x=374, y=328)
10-16 18:38:39.952 12855 12891 I System.out: Point(x=509, y=327)
10-16 18:38:39.952 12855 12891 E PowBotNative: ProcessInputEvent(134217728, 0x7609d7053880)
10-16 18:38:39.952 12855 12891 I System.out: event at 547.0 351.0 Point(x=509, y=327)
10-16 18:38:39.952 12855 12958 I TouchWaiter: got all wanted touch events
10-16 18:38:39.953 12855 12930 I TouchWaiter: wait for touch succeeded
10-16 18:38:39.976 12855 12958 I ActionWaiter: Received expected action - NpcActionEvent(name=Banker, id=11945, level=-1, interaction=Bank)
10-16 18:38:39.979 12855 12930 I System.out: Time to interact: 2437
```
It looks like it's generating two points for some reason?  The x coordinate is very different for them in this example, so not sure what's going on there.

**Comment by constt** [comment]
@5Henveru2 It generates a point when queued and a point when the touch is being invoked.

I just made a substantial improvement, could you please test in 20.

**Comment by 5Henveru2** [comment]
It's been significantly improved, thank you.
