### ISSUE TITLE
Menu item debug does not work on items in bank [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#13]
**Describe the bug**
With the menu debugger on, right clicking on item does not pull it's menu actions 

**To Reproduce/Line of code causing issue**
Open bank, turn on Bank Debug, right click an item

**Expected behavior**
Menu items listed by debug

**Screenshots**

![image](https://user-images.githubusercontent.com/64224090/184858614-58dbe124-9d0d-46e0-9d3c-7b9bd584649f.png)
![image](https://user-images.githubusercontent.com/64224090/184858688-b79df607-33e9-44b7-8d8b-0ff09922397b.png)

**Comment by constt** [comment]
https://i.imgur.com/0iUjjki.png

@Protoprize can you re-test

**Comment by ghost** [comment]
@constt  Fixed 👍
