### ISSUE TITLE
[BUG] Game.Logout() returns false always

### ISSUE THREAD

**Issue by gutizia** [powbot/issues#131]
**Describe the bug**
calling Game.Logout() returns false even when successfully logging out

**To Reproduce/Line of code causing issue**
val result = Game.logout()

**Expected behavior**
i expect the function call to wait a bit longer for the actual results of clicking logout.

**Logs**
[2022-10-17 12:42:09.653][TestScript] logging out immediate result: Game.loggedIn=true, result=false
[2022-10-17 12:42:11.832][TestScript] logging out result after 2 seconds: Game.loggedIn=false, result=false

**Comment by constt** [comment]
pushed fix

**Comment by iDznPB** [comment]
Still returns false on latest update

**Comment by constt** [comment]
Pushed another fix

**Comment by iDznPB** [comment]
Issue still persists

**Comment by constt** [comment]
fixed
