### ISSUE TITLE
[BUG] WebWalker stuck trying to take boat to kourend from port sarim

### ISSUE THREAD

**Issue by gutizia** [powbot/issues#132]
**Describe the bug**
when using webwalker to kourend from main land, the script attempts to interact with npc to board boat to kourend when he's not loaded in because the player is too far away.
I've been using webwalker a lot coming from falador to port sarim, this only happens maybe 5-10% of the time

**To Reproduce/Line of code causing issue**
webwalk to kourend, approaching port sarim from the north, doesn't happen all the time

**Expected behavior**
i expect bot to walk further towards the boat before attempting to board. iirc npcs don't load until at least within 16 tiles of them, so at least that

**Screenshots**
![image](https://user-images.githubusercontent.com/51299340/196276364-b5268c14-3380-40cd-99cf-ad009813b392.png)
exact location bot got stuck on (forgot to put location on in debug settings)

**Logs**
see attached file

[error.txt](https://github.com/powbot/issues/files/9804307/error.txt)

**Comment by constt** [comment]
@gutizia please try Dax WW
