### ISSUE TITLE
[BUG] Bank.withdraw(id, Amount.ALL) doesn't work

### ISSUE THREAD

**Issue by Krulvis** [powbot/issues#133]
**Describe the bug**
Bank.withdraw(id, Amount.ALL) doesn't withdraw.
All other Bank.Amount values work, ALL is the only one that seems to not work.

**To Reproduce/Line of code causing issue**
`Bank.withdraw(id, Amount.ALL)`

Since update 19/10/2022

**Comment by constt** [comment]
should be fixed

**Comment by iDznPB** [comment]
Beautiful, confirmed working
