### ISSUE TITLE
[BUG] obj missing name

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#135]
**Describe the bug**
this object WAS working fine, now has no name
![image](https://user-images.githubusercontent.com/34009165/196770330-ff7a1edc-908e-48bb-8816-ffcf3b888e83.png)

**Expected behavior**
to have name - "Portal"

**Comment by benpoulson** [comment]
What _was_ the name before?

**Comment by iDznPB** [comment]
My bad. Should be "Portal"

**Comment by constt** [comment]
@iDznPB try in 20

**Comment by iDznPB** [comment]
@constt 
no joy
![image](https://user-images.githubusercontent.com/34009165/196898794-4b43dcdc-f904-4ddc-b30a-05d51f99b0f4.png)

**Comment by constt** [comment]
@iDznPB try in 20

**Comment by iDznPB** [comment]
@constt 
![image](https://user-images.githubusercontent.com/34009165/196922031-10eefb5c-553c-4d46-8cf0-c98783c0aa3b.png)
still no change,

**Comment by constt** [comment]
ok @iDznPB worked out what was wrong should be good in 20

**Comment by iDznPB** [comment]
wahay all sorted, thank you
