### ISSUE TITLE
[BUG] Wonky dancing models

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#137]
**Describe the bug**
Model dancing around like it's high af 
- Rogues den, gates

**Expected behavior**

**Screenshots**
https://i.gyazo.com/0f5b481538f882bf88c6f5715bb26da9.mp4

**Comment by constt** [comment]
@iDznPB I've added a new interaction type `BoundingModel` could you try that please

**Comment by iDznPB** [comment]
@constt 
Thought this might be an issue;
![image](https://user-images.githubusercontent.com/34009165/197276160-3f065640-70d8-4649-b9aa-af7bf6768ac5.png)
it's based on the tile, but the object isn't directly on the tile, since the model doesn't overlap the object at all, it's less reliable than the dancing one

**Comment by iDznPB** [comment]
@constt with the new development build installed 2 minutes ago, all object model orientations are dancing around 
https://i.gyazo.com/37d0c48ccb55401e3332fca2fdf2a96b.mp4
