### ISSUE TITLE
[BUG] Magic.Spell.HOME_TELEPORT.cast() always returns false

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#138]
**Describe the bug**
Even though it successfully clicks the home teleport button, it always returns false.

**To Reproduce/Line of code causing issue**

```
System.out.println(org.powbot.api.rt4.Magic.Spell.HOME_TELEPORT.cast());
```

**Expected behavior**
It should return true if it successfully clicks the teleport button, false if it does not.

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by iDznPB** [comment]
Can you try the following?
Magic.Spell.HOME_TELEPORT.cast("Cast")
Since it's a multi option spell, I believe it requires the extra param to confirm if it was successful

**Comment by 5Henveru2** [comment]
`Magic.Spell.HOME_TELEPORT.cast("Cast")`
Still returns false when clicked

**Comment by constt** [comment]
@5Henveru2 please try in 20

**Comment by iDznPB** [comment]
@5Henveru2 any update?

**Comment by 5Henveru2** [comment]
> @5Henveru2 please try in 20

org.powbot.api.rt4.Magic.Spell.HOME_TELEPORT.cast() still returned false despite successfully home teleporting

**Comment by constt** [comment]
@5Henveru2 fixed this

**Comment by 5Henveru2** [comment]
Fixed
