### ISSUE TITLE
[BUG] Bank scrolling - not scrolling enough

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#143]
**Describe the bug**
Tries to withdraw items through the bar as per below screenshot

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/197541825-93d812e8-b355-491e-8c22-d9b8dfa87441.png)

**Logs**
[WARNING] Received unexpected action while waiting for Withdraw-X - WidgetActionEvent(widgetId=786451, interaction=Insert, name=, id=1)

**Comment by constt** [comment]
@iDznPB still an issue?

**Comment by iDznPB** [comment]
seems to be working fine now
