### ISSUE TITLE
[BUG] Auto login not clicking "Play Now"

### ISSUE THREAD

**Issue by Jinster80** [powbot/issues#144]
**Describe the bug**
During login bot does not click "Play now", it gets stuck until i click the client 

**Screenshots**
https://gyazo.com/5952e67cd3e55315396103837e8b093e

**Logs**
10-26 23:19:16.927  5007  5128 I AutoLogin: known ign is [], saved is [null]
10-26 23:19:16.927  5007  5128 I AutoLogin: Hitting play now
10-26 23:19:24.167  5007  5128 I AutoLogin: known ign is [], saved is [null]
10-26 23:19:24.167  5007  5128 I AutoLogin: Hitting play now
10-26 23:19:32.712  5007  5128 I AutoLogin: known ign is [], saved is [null]
10-26 23:19:32.712  5007  5128 I AutoLogin: Hitting play now

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: PIE
 - Arch: ARM

**Comment by gavinnn101** [comment]
you're leaking your ingame name in the logs fyi

**Comment by constt** [comment]
@Jinster80 please try now
