### ISSUE TITLE
[BUG] Components.stream(id) does not pull all components

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#145]
**Describe the bug**
If you compare the results of:
`Components.stream(id)`
to the results of:
`Widgets.widget(id).getChildren()`
the Widgets method returns all components that you'd find in the Widget explorer, however Components.stream only returns some of the present components.

The example I've looked at is not the easiest to reproduce, but the Doomsayer warning when you enter Mort Myre swamp is under Widget 580, and the Components.stream(580) method only returns 2 components, but grabbing them through Widgets returns the entire list of components you'd expect.

**Expected behavior**
Components.stream(id) should return all components that fall under the widget with that id

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by constt** [comment]
@5Henveru2 does this still happen?
