### ISSUE TITLE
[BUG] Dax WW - Movement.moveToBank() with jewellery in inventory broken

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#149]
**Describe the bug**
Movement.moveToBank() with dueling ring in invent seems to break

**To Reproduce/Line of code causing issue**
1. turn on dax in settings
2. Movement.moveToBank()
3. ded

**Expected behavior**
take me to a bank

**Screenshots**
https://gyazo.com/27414f1bd943185c80a00103184674e8

**Logs**
since it tries to print out the itemorg.powbot.api.blah.blah.blah no idea what it's looking for but it SHOULD, "Rub" then select from the chat menu that appears.
```
[INFO] trying to click menu itemorg.powbot.api.rt4.Menu$TextFilter@245789c
[SEVERE] Menu item doesn't exist - [Wear Ring of dueling(8), Use Ring of dueling(8), Rub Ring of dueling(8), Drop Ring of dueling(8), Examine Ring of dueling(8), Cancel]
[INFO] trying to click menu itemorg.powbot.api.rt4.Menu$click$1@6fc12a5
[INFO] found menu item at 5
[] GameActionEvent(v0=-1, widgetId=-1, rawOp=1006, id=-1, interaction='Cancel', rawEntityName='', mouseX=683, mouseY=223)
[WARNING] Received unexpected action while waiting for (Rub|Teleport|(?i).*Castle Wars.*) - GameActionEvent(v0=-1, widgetId=-1, rawOp=1006, id=-1, interaction='Cancel', rawEntityName='', mouseX=683, mouseY=223) 
```

**Comment by gutizia** [comment]
I have same issue with jewellery items for my farming script, if possible would love a seperate function to call webwalking without teleports in mind to avoid dax webwalker to use my precious jewellery charges to save a few tiles of walking

**Comment by 5Henveru2** [comment]
Switched from using .click to .interact for items, and that should fix this.  Let me know otherwise!

**Comment by 5Henveru2** [comment]
Hey @iDznPB can you confirm that this is fixed?

**Comment by iDznPB** [comment]
> Hey @iDznPB can you confirm that this is fixed?

Sorry for the delay! I just tested it, I had a ring of dueling in my inventory, as well as a games necklace and I was at burthorpe (games necklace) tele spot, it ran be down past taverly, through Whitewolf mountain (which nearly killed me) then banked at catheryby, so I'm not really sure I'll be honest!

**Comment by 5Henveru2** [comment]
I'm not sure why I haven't thought of this before, but I can add some path weight to White wolf mountain if we are under a certain combat level or hitpoints level.  Any suggestion on thresholds for that?

**Comment by 5Henveru2** [comment]
If the path is too heavy, it should pick to use an available teleport if possible

**Comment by iDznPB** [comment]
I mean I'm 50hp but was wearing graceful so no defensive bonuses, when it fails goes to [INFO] Could not find next Edge it can take a good 7-15 seconds to continue, when that's 2-3 times over the mountain, they can pepper you. 

However, that being said, I'd probably say <50hp find an alternative otherwise it _should_ be fine.

But any idea why it didn't use either the games necklace or dueling ring to teleport to a bank <10 tiles away but rather ran this path instead?
![image](https://user-images.githubusercontent.com/34009165/204320883-44c3c03a-957f-4c49-a405-7b2c0165e9a9.png)

**Comment by iDznPB** [comment]
I'm a retard.

Dax was turned off on this instance of BS

**Comment by iDznPB** [comment]
worked like a charm, will close thank you!

**Comment by 5Henveru2** [comment]
I was going to say that it sounds like the wrong log info!  But powbot's object cache can somehow find objects VERY far away, so it probably detected the bank object in catherby.  Constt was running into weird issues where it would see the Al Kharid bank from lumbridge teleport spot and pick that as the nearest bank.
