### ISSUE TITLE
[BUG] No way to cancel starting a script

### ISSUE THREAD

**Issue by okazakikun** [powbot/issues#15]
**Describe the bug**
When selecting SDN scripts there's no X or cancel, only start script

**To Reproduce/Line of code causing issue**
1. Click play button
2. Select script
3. ????
4. profit

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Additional context**
If you click the wrong script you generally want to be able to cancel/close it without starting it

![image](https://user-images.githubusercontent.com/26844787/184957000-02acdaa3-039b-452b-92ff-860cf9e92c2c.png)

**Comment by constt** [comment]
@okazakikun this should be resolved in 20mins please close if so.

**Comment by iDznPB** [comment]
Confirmed this is working and can be closed @okazakikun @constt
