### ISSUE TITLE
[BUG] Combat.specialAttack(true) is broken in pvp

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#152]
**Describe the bug**
Combat.specialAttack(true) uses the spec orb by the map, which is fine for 99% of cases. The only time it's disabled is when in pvp.

**Expected behavior**
Use the special bar from the attack tab

**Screenshots**
Non-wildy/pvp area
![image](https://user-images.githubusercontent.com/34009165/200570018-6054a539-e1f3-422d-aa1d-0bf6d4def615.png)

Wild/pvp area
![image](https://user-images.githubusercontent.com/34009165/200570082-aa34f65a-d250-43d1-89d5-56313b59db77.png)

What it should use instead
![image](https://user-images.githubusercontent.com/34009165/200570129-b7d67a81-c0c3-402d-9ff4-7a643074be55.png)

**Comment by constt** [comment]
@iDznPB fixed please test

**Comment by iDznPB** [comment]
@constt this now uses the attack tab for all specs, the only time it's needed is when you're in the wild. Noticed it while I was woodcutting when it should still use the orb

**Comment by constt** [comment]
@iDznPB my bad I didn't update constants.props

**Comment by iDznPB** [comment]
closed as completed
