### ISSUE TITLE
[BUG] Script name change, creates duplicate script SDN entry.

### ISSUE THREAD

**Issue by Zibele** [powbot/issues#159]
**Describe the bug**
Even, though my script has a script id, when I changed the name of my script, and its category, the SDN still kept the old one and created another one with the a new name.

**Expected behavior**
Single entry of the script on the SDN, with the new name.

**Screenshots**

![d0f6e01f5850d91f17c3bd37e3d6ca60](https://user-images.githubusercontent.com/33414379/202000070-05acaaf1-9c9f-4c14-af97-32417432de9a.png)

**Comment by constt** [comment]
You need to set scriptId in the manifest which you can get from /authoredscripts. Let an admin know if you need to delete one
