### ISSUE TITLE
[BUG]NPC name null

### ISSUE THREAD

**Issue by Nickert1337** [powbot/issues#161]
**Describe the bug**
Thug names are null (again)

**To Reproduce/Line of code causing issue**
1. Go to thugs.
2. Open interactive objects
3. They are null

**Expected behavior**
Non null bandits

**Screenshots**
![image](https://user-images.githubusercontent.com/98966743/202195542-33dace9a-613d-4ab9-ad7d-97acc32f98b3.png)

**Comment by constt** [comment]
@Nickert1337 stioll happening?
