### ISSUE TITLE
[BUG] HintArrow broken

### ISSUE THREAD

**Issue by PTYB** [powbot/issues#163]
**Describe the bug**
HintArrow.X/HintArrow.Y return 0

**To Reproduce/Line of code causing issue**

```
HintArrow.x() /HintArrow.y()
```

**Expected behavior**
Should return correct x/y

**Emulator or device (please complete the following information):**
 - Bluestacks
 - Android Pie
 -  ARM64

**Additional context**

**Comment by ghost** [comment]
Extra issue
```
HintArrow.INSTANCE.npc().valid())
```
Also returns incorrect details. Video below
https://user-images.githubusercontent.com/64224090/202846303-b8d86d63-f7e0-469e-a1c4-235cf5c9e287.mp4


It manages to pull the correct NPC after hint arrow shows up. Then once it changes, takes like 3 secs and it goes back to a random NPC the hint arrow api pulled before.

**Comment by constt** [comment]
@Protoprize would type 0 ever be valid?

**Comment by constt** [comment]
pushed fix

**Comment by MichalTDev** [comment]
Works :)
