### ISSUE TITLE
[BUG] Dax WW - Failing to find path using spirit tree

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#164]
**Describe the bug**
I saw it use the spirit tree like twice, but now it just says no path found

**Expected behavior**
Use the spirit tree rather than saying no path found

**Screenshots**
From this tree
![image](https://user-images.githubusercontent.com/34009165/202906919-bd67100d-fa43-4afa-a638-bf6e2a5c9657.png)
to this tree
![image](https://user-images.githubusercontent.com/34009165/202906940-b2f95749-f47f-4242-bc10-22b66fa579cc.png)

**Logs**
```
,"requests":[{"end":{"x":2462,"y":2450,"z":0},"start":{"x":3161,"y":3478,"z":0}},{"end":{"x":2462,"y":2450,"z":0},"start":{"x":2994,"y":3377,"z":0}},{"end":{"x":2462,"y":2450,"z":0},"start":{"x":2535,"y":3861,"z":0}},{"end":{"x":2462,"y":2450,"z":0},"start":{"x":3313,"y":3233,"z":0}},{"end":{"x":2462,"y":2450,"z":0},"start":{"x":2440,"y":3090,"z":0}},{"end":{"x":2462,"y":2450,"z":0},"start":{"x":3150,"y":3635,"z":0}},{"end":{"x":2462,"y":2450,"z":0},"start":{"x":3181,"y":3507,"z":0}}
```

**Comment by 5Henveru2** [comment]
Hi Dan, I think we spoke briefly on discord about this but let me know if you can get the log for this again.  The end tile that you have listed in the request above is in the middle of black nothingness (tile 2462, 2450, 0), so that is probably why it wasn't returning a path.

**Comment by iDznPB** [comment]
> 

I knew I'd seen it work before! looks like I fat fingered it, it should have been 2462 **3**450, 0.

Will close, sorry to have wasted your time!
