### ISSUE TITLE
[BUG] Auto hide UI does not hide the UI

### ISSUE THREAD

**Issue by ghost** [powbot/issues#165]
**Describe the bug**
The option does not hide the UI. It seems to be drawing the same last frame over and over again.

**To Reproduce/Line of code causing issue**
Enable the option

**Expected behavior**
UI gets yeeted

**Comment by constt** [comment]
@Protoprize Is the same frame being drawn causing issues? This was actually intended so that you could see gui

**Comment by ghost** [comment]
Ahh, makes sense. Looked stuck so thought it was broken
