### ISSUE TITLE
[BUG] Inventory.stream() returns empty while switching from widgets to cache

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#168]
**Describe the bug**
If the inventory is streamed while the inventory source is moving from cache to widgets or witdgets to cache, it returns empty. This causes issues when using the stream to check if things exist in the inventory before trying to interact with them.

The most recent use case was turning off alching while doing agility if the alch item doesn't exist. Selects the item to alch which moves from widgets to cache, then reads .isEmpty() in the inventory and triggers turning off said feature.

Easily workaroundable but still a QOL bug imo.

**Expected behavior**
Inventory stream() to wait for stream source to finish loading before returning

**Comment by constt** [comment]
pushed a fix @iDznPB

**Comment by ghost** [comment]
Started happening again on dev client

**Comment by iDznPB** [comment]
Miscomunication, reclosing
