### ISSUE TITLE
[BUG] Bank.withdraw(String, ALL) returns false when Bank.withdrawModeNoted() is true

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#176]
**Describe the bug**
When withdrawing items as notes the Bank.withdraw(String, amount) returns false when it should be true

**To Reproduce/Line of code causing issue**

```java
if (Bank.withdrawModeNoted(true)) {
        System.out.println("Noted");
	if (Bank.withdraw(item.name(), Bank.Amount.ALL)) {
		System.out.println("Withdrawn item");
        } else {
                System.out.println("Failed to withdraw");
        }
}
```

**Expected behavior**
Return true. The item was successfully withdrawn into my inventory.
I assume it's looking for a match on item ID?

**Comment by iDznPB** [comment]
It also has a huge time out to return false too

**Comment by constt** [comment]
fixed in next

**Comment by iDznPB** [comment]
Resolved, thanks!
