### ISSUE TITLE
[BUG] Walking from under slayer tower to canifis bank

### ISSUE THREAD

**Issue by PTYB** [powbot/issues#177]
**Describe the bug**
Can't find path from under slayer tower to canifis bank

**To Reproduce/Line of code causing issue**

Try to walk to `x=3512, y=3479, floor=0` from `x=3424, y=9936, z=3, regionID=13723`

**Expected behavior**
Should find path

**Comment by 5Henveru2** [comment]
Hey, can you send me the logs on discord (Elias)?  This route should be supported

**Comment by PTYB** [comment]
Closing, will open if occurs again
