### ISSUE TITLE
ScriptManager.pause causes script to hang/no control of thread [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#18]
**Describe the bug**
The method causes the script to hang, you can start running other scripts along side it.

**To Reproduce/Line of code causing issue**

Start script that uses the method

```ScriptManager.INSTANCE.pause();```

Start script button will re-appear, can't stop the currently 'paused' script. If you start another, it seems to start on a new thread. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64224090/185072260-e59becfb-93f9-4814-bba7-ca7ebaf789c5.png)

**Comment by benpoulson** [comment]
I think this has always been an issue, even before native. I think it's an issue with calling pause within the onStart specifically. (For a while I had to hack my scripts to use a latching boolean within the poll() method.)
