### ISSUE TITLE
[BUG] Clicking GroundItems that are on objects (tables, crates)

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#180]
**Describe the bug**
The client attempts to click GroundItems that are stored on objects as if they were still on the ground, so the clickpoint that is generated is too low.

**To Reproduce/Line of code causing issue**
1. Go to Lumbridge castle kitchen
2. Try to pick up the Knife grounditem which is on a crate
3. It will struggle to pick it up (but probably eventually succeed, depending on your camera pitch/yaw)

**Expected behavior**
Either the client should adjust the click height if it can reliably determine this scenario, or if we could have a method accessible to add some click height to ground items that would suffice.

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by constt** [comment]
Ground item models were broken, fixed now and should be good.
