### ISSUE TITLE
[BUG] All floor object models are null

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#181]
**Describe the bug**
Floor objects return valid, but they have no model

**To Reproduce/Line of code causing issue**

```
GameObject tile = Objects.stream().within(3).id(1264).first(); // or any floor object
if(tile. Valid()) {
      System.out.println((tile.model()==null)+""); // this returns true, and .draw() does nothing
}
```

**Expected behavior**
model to be alive, not ded :man_shrugging:

**Comment by constt** [comment]
This has been fixed
