### ISSUE TITLE
[BUG] Hint arrow API reporting wrong X and Y coords and no object def

### ISSUE THREAD

**Issue by ghost** [powbot/issues#183]
**Describe the bug**
The hintarrow API reports incorrect information, also does not contain object definitions (only player/npc).

Also, after hintarrow changes tile, the x and y coords do not get updated. Not correlated to the above issue as when a hint arrow appears, it seems like it randomly generates x and y from any tile in the region the player is in.

**Comment by constt** [comment]
@Protoprize where's somewhere i can test it

**Comment by ghost** [comment]
Seems to have been fixed in between updates :)
