### ISSUE TITLE
[BUG] Shantay Pass Doomsayer warning components not reading properly in api

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#185]
**Describe the bug**
While the client can clearly see the components under widget 565, API calls are not pulling all relevant components.  See code example below.  

**To Reproduce/Line of code causing issue**
1. Go to Shantay Pass.
2. Run the below code

```
        Components.stream(565).anyMatch(c -> {
            String txt = c.text();
            if(txt.length() == 0)
                return false;
            boolean matches = txt.contains("Proceed regardless");
            System.out.println("[TEST] Found component with text: " + txt + ", matches: " + matches);
            if(!matches){
                return false;
            }
            System.out.println("[TEST] Found matching component! Clicking it.");
            return c.click();
        });
```
This gets print out from that:
```
[TEST] Found component with text: Don't ask me this again, matches: false
```
However, there are numerous components that have text under widget 565, but none of them are picked up in the stream.
Here is what I'm looking at on the client:
![image](https://user-images.githubusercontent.com/96345909/208435074-d4d2f543-b7bc-48d8-9d14-0db5adfa8bf6.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks  
 - OS: Android Pie  
 - Arch: ARM64

This is a subset of code utilized by daxwalker, so currently we are stuck in the Shantay Pass unless the user has already ignored this doomsayer warning.

**Comment by constt** [comment]
@5Henveru2 is this an issue now?

**Comment by 5Henveru2** [comment]
Doomsayer warnings have a new fancy enum and should be all good.
