### ISSUE TITLE
[BUG] Object streams sometimes take a very long time to return values

### ISSUE THREAD

**Issue by ghost** [powbot/issues#188]
**Describe the bug**
Object streams take a while to return in some cases. Krulvis reported this in our scripter chat, posted some snippets below with descriptions:

```Kotlin
val timeToFindObj = measureTimeMillis {
            obj = Objects.stream().name("Portal").action("Lock").isNotEmpty()
        }
script.log.info("Found portal in $timeToFindObj ms")
```
This results in:

```log
[INFO] Found portal in 5154 ms
```

Removing the `action("Lock")` check results in the streams still taking a while but not as long:

```log
[INFO] Found portal in 1411 ms
[INFO] Last loop at: 1672225173542 was 0ms ago
[INFO] Found portal in 1331 ms
[INFO] Last loop at: 1672225174876 was 0ms ago
[INFO] Found portal in 1395 ms
[INFO] Last loop at: 1672225176275 was 0ms ago
[INFO] GameObjectActionEvent(name=Portal, id=15481, interaction=Home, tile=Tile(x=2755, y=3176, floor=0, localX=51, localY=48))
[INFO] Found portal in 1401 ms
[INFO] Last loop at: 1672225177678 was 0ms ago
[INFO] Found portal in 2792 ms
[INFO] Last loop at: 1672225180474 was 0ms ago
[INFO] Found portal in 1155 ms
[INFO] Last loop at: 1672225181632 was 0ms ago
[INFO] Found portal in 1070 ms
[INFO] Last loop at: 1672225182705 was 1ms ago
[INFO] Found portal in 1092 ms
[INFO] Last loop at: 1672225183802 was 1ms ago
[INFO] Found portal in 1026 ms
[INFO] Last loop at: 1672225184831 was 0ms ago
[INFO] Found portal in 1048 ms
[INFO] Last loop at: 1672225185881 was 1ms ago
```

These examples are based on entering and leaving a player owned house, where there are a **TON** of floor objects.

![image](https://user-images.githubusercontent.com/64224090/209817822-462323cc-8923-4da5-ad7b-c41700d84beb.png)

I am not aware of how the callbacks work currently, but if it's not an issue with them, could a possible move to separate object functions help? For example, we could have an overall

```Java
Objects.stream
```

As we do right now. But if we wanted to narrow it down without pulling every single object from the game, we could have 

```Java
FloorObjects.stream
```
```Java
GameObjects.stream
```
```Java
WallObjects.stream
```

I could very much be wrong here so please correct me if I am, but if we currently pull all objects with `Objects.stream` and then narrow them down to specific options, the solution above would narrow it down even more, and would result in better return times.

**Comment by 5Henveru2** [comment]
You should be able to use Objects.stream(distance, ObjectType) to accomplish that, correct?  In areas like POH where there are a ton of objects, those streaming methods don't work too well and I think constt has done a lot of optimizations already.  Constt can probably weigh in with the most efficient ways to reduce computation time, but adding the ObjectType has drastically reduced the time for me (especially when I'm not looking for FloorObjects)
