### ISSUE TITLE
[BUG] Quiver cache not updating in bank

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#189]
**Describe the bug**
Equipment tab - more specifically the quiver updates using both the widgets and the cache which is literally a god send. However  recently when equipping items directly in the bank, the cache either pulls the wrong number (gif 1) or doesn't update at all (gif 2).

```
Rendering.drawString("QUIVER ITEM: "+ Equipment.itemAt(Equipment.Slot.QUIVER).name()+" x"+ Equipment.itemAt(Equipment.Slot.QUIVER).stackSize(), 400, 400);
```

**Expected behaviour**
Equipment stream to pull the correct values from the cache. 
For clarity, this was working a few weeks ago.

**Screenshots**
https://i.gyazo.com/cdeaaf96bb14c869c7e3377027471c41.mp4
https://i.gyazo.com/3959c70213277d17bcbc1f483860e186.mp4

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Additional context**
This was working a few weeks ago so it's possible for it to work, just something recently would have broke it,

**Comment by constt** [comment]
@iDznPB now using varps for the quiver so it should be relaible

**Comment by iDznPB** [comment]
Resolved
