### ISSUE TITLE
[BUG] Incorrect combat level

### ISSUE THREAD

**Issue by Barcodeyboi** [powbot/issues#190]
**Describe the bug**
Issue getting the correct combat level of the player. Currently api returns 1 instead of the correct combat level.

**To Reproduce/Line of code causing issue**
private val logger = Logger.getLogger(this.javaClass.name)
logger.info(Skill.Combat.realLevel().toString())
logger.info(Skills.realLevel(Skill.Combat).toString())

both return 1

**Expected behavior**
Return the correct combat level of the player

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by Barcodeyboi** [comment]
Fixed the issue with Players.local().combatLevel. This returns the correct combat level

**Comment by constt** [comment]
have patched Skills
