### ISSUE TITLE
[BUG] Missclick on GameObject.interaction("use"); (Furnace)

### ISSUE THREAD

**Issue by xpelch** [powbot/issues#192]
**Describe the bug**
The interact miss the use actions on a furnace, happened on tutorial island, but according to Proto, it happened elsewhere too.
Not much to say about it, beside the fact that it looks like on the image provided. The action box renders below, and the click misses it entirely.

**To Reproduce/Line of code causing issue**
```
val furnace = Objects.stream().name("Furnace").nearest().first();
  if (furnace.interact("Use")) {
                Condition.wait( ... , 600, 10);
            }
```

**Expected behavior**
Should click the actions correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/77986237/210268790-79142d25-7bfd-43f7-9b46-54b30051b5d5.png)

**Logs**
If applicable, add logs relating to the issue.

**Emulator or device (please complete the following information):**
 - Device/Emulator: BlueStacks
 - OS: Android Pie
 - Arch: ARM64

**Additional context**

**Comment by constt** [comment]
@xpelch 
Please  try:

```
if (furnace.interactionType(ModelInteractionType.HullQuick).interact("Use")) {
```
