### ISSUE TITLE
[BUG] modifiedColors hook is broken

### ISSUE THREAD

**Issue by Krulvis** [powbot/issues#195]
**Describe the bug**
object.modifiedColors() should return a list of modified colors but always returns an empty list.

**To Reproduce/Line of code causing issue**
```kotlin
Objects.stream(50).filtered { it.modifiedColors().isNotEmpty() }.forEach {
            log.info("Found obj with colors: ${it.name}, ${it.modifiedColors().joinToString()}")
        }
```

**Expected behavior**
At least a couple of log outputs with objects with modified colors (minable rocks use this to show they can be mined).
Standing in an area with minable rocks should always result in some rocks with colors.

**Logs**
No logs is the problem :(

**Comment by constt** [comment]
@Krulvis should be working
