### ISSUE TITLE
[BUG] Wrong Object Name

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#196]
**Describe the bug**
Should be a "Fire" but is "Mysteriuous Ruins", it does however have the correct model.

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/211812949-e124cd6e-9075-4cba-8c2b-6cf049fc3545.png)
![image](https://user-images.githubusercontent.com/34009165/211813087-2e33ddf1-efbe-436f-b58f-3c1d16c5fdad.png)
(In rogues den)

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: 11
 - Arch: ARM

**Comment by iDznPB** [comment]
Can confirm fixed

**Comment by iDznPB** [comment]
@constt 
Looks like the fix in place broke something that wasn't broken before
![image](https://user-images.githubusercontent.com/34009165/214245205-f55435be-d26b-4dd9-8681-764ffb7ac452.png)
![image](https://user-images.githubusercontent.com/34009165/214561677-9186b858-857f-4f45-aa23-ee5bd609e814.png)

**Comment by iDznPB** [comment]
After todays update, the objects that were fixed from the work around, are now broken again

**Comment by adivorcedfork** [comment]
All the objects in Giant's Foundry are broken as well.
