### ISSUE TITLE
[BUG] World Hopping

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#198]
**Describe the bug**
https://discord.com/channels/341014842745815054/1063574203686715443
User reporting issues scrolling, missing the scroll bar as per screenshot
and also hopping to the incorrect world i.e. F2P worlds.

**Expected behavior**
Can we just implement do action hopping already.. :)

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/212467419-88f56843-d66b-4be4-9120-1f409e3a0951.png)

**Comment by constt** [comment]
@iDznPB pushed a fix

**Comment by iDznPB** [comment]
Confirmed fixed, thanks!
