### ISSUE TITLE
Player animation Debug "Animation: 0" [BUG]

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#2]
**Describe the bug**
Animation remains at 0, doesn't change when player is idle.
Secondary issue: Most scripts revolve around -1 being the idle animation rather than 0.

**To Reproduce/Line of code causing issue**
1. turn on Animation debug
2. Perform an action where your animation changes, i tried woodcutting & punching

**Expected behavior**
I'd expect the animation to change according to the animated character.

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/184601416-158e70bf-0f1e-44f8-aaf7-dceae66ac0bb.png)

**Logs**
No logs printed when turning on or off / or animating

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Pie64
 - Arch: ARM

**Additional context**

**Comment by constt** [comment]
This has been resolved
