### ISSUE TITLE
Paint is buggy [Minor][BUG]

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#20]
**Describe the bug**
Paint overlays are glitchey, resizing, flashing, flickering

**To Reproduce/Line of code causing issue**
1. Start a script (I chose "walker")

**Expected behavior**
Non flashing/glitching paint

**Screenshots**
https://gyazo.com/e771575b75a66f07aad36f41e28e3003

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
Have removed seperate render thread for now @iDznPB
