### ISSUE TITLE
[Daxwalker] Skills Necklace teleports broken

### ISSUE THREAD

**Issue by nschaa** [powbot/issues#203]
@ Elias

When Daxwalker tries to use Skills Necklace to teleport, it fails to interact with the Inventory + Skills Necklace and teleport to destination.

When I manually bring up the Skills Necklace Teleport interface, it can successfully click the correct teleport and continue on so I think the issue is trying to initially interact with the Skills Necklace to bring up the teleport menu.

Logs show that it can recognize which teleport it needs to select (ex: SKILLS_COOKING_GUILD) but fails to actually execute the teleport and just loops. Tested for other Skills Necklace locations and they all have the same issue.

[log_2.txt](https://github.com/powbot/issues/files/10492138/log_2.txt)

**Comment by 5Henveru2** [comment]
@constt 
this was fixed in this commit https://github.com/powbot/walking-api/commit/19d921b59a6deba456a894411cd0e9c953cb70cb
