### ISSUE TITLE
[BUG] Missing Object

### ISSUE THREAD

**Issue by nschaa** [powbot/issues#204]
@constt 

Interactive GameObject Gnome Landing Lights seems to be broken/missing.

https://i.imgur.com/kFDPHAU.png
https://i.imgur.com/3uY1rxg.gif

There are 3 pairs of Gnome Landing lights and each pair should have a unique Object ID (5823, 5821, 5822, 5820) but they can only be identified by their I = 5815 ids.

When trying to draw them nothing shows.

**Comment by iDznPB** [comment]
@nschaa any update?

**Comment by nschaa** [comment]
> 

Yep works now, thanks!
