### ISSUE TITLE
[BUG] Game.logout() failure timeout approx. 15 seconds

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#211]
**Describe the bug**
if Game.logout() fails, takes approx 15 seconds to timeout

**Expected behavior**
Check for missclicks or not successfully pressing the widget, also early return on
"You can't log out until 10 seconds after the end of combat."

**Comment by constt** [comment]
pushed improvements for both issues

**Comment by iDznPB** [comment]
Working well, will close, thank you!
