### ISSUE TITLE
[BUG] Cached objects updating ID's

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#217]
**Describe the bug**
Cached an object, in this case a rock to mine, checking .valid() and always returns true even after it's been mined
checking a new stream with the cached ID and tile; the ID changes, so the new stream returns true but for the new ID not the old

**To Reproduce/Line of code causing issue**
1. cache object in this case iron ore; 11364
2. mine rock
3. see cached objects ID chance to 11390 and valid() return true
4. See problem

**Expected behavior**
cached object not to live update things like name/ID etc as they're identifying markers

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: 11
 - Arch: A64

**Comment by constt** [comment]
heh this is only for rocks cause they share the same name

Applied a patch

**Comment by iDznPB** [comment]
I see!
Closing as completed
