### ISSUE TITLE
[BUG] Npc health percent returns 1.0 when an npc has 0.0% and is dying

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#218]
**Describe the bug**
An npc returns 0.0% briefly when you kill them, but when their dying animation begins the health resets to 1.0.  

**To Reproduce/Line of code causing issue**
1. Add npc health percent and animation to paint builder
2. Kill the npc
3. Watch the health percent reset to 1.0 when their dying animation begins

**Expected behavior**
Npc health should stay at 0.0 while they/their health bar remains present

**Comment by constt** [comment]
@5Henveru2 try now should be gucci
