### ISSUE TITLE
Players.local().inMotion() is broken [BUG]

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#22]
**Describe the bug**
Speed is static set to 32 and in turn inMotion is always true.

**To Reproduce/Line of code causing issue**
1. turn on local player and see Speed: 32

**Expected behavior**
inMotion to return true when char is moving

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/185231973-b46bc047-9582-4d96-8c92-a62c61a14793.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB Removed speed in favor of using animations, please confirm (20mins)

**Comment by iDznPB** [comment]
Tested and inMotion now works
