### ISSUE TITLE
[BUG] Bank null placeholders

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#220]
**Describe the bug**
Empty placeholder spots are returning in the stream

**To Reproduce/Line of code causing issue**
1. Turn on bank debug

**Expected behavior**
Not return ID 6512 as it's an empty space

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/218734989-b106052c-f52d-4f51-b46d-1c593da94f7f.png)

**Comment by constt** [comment]
@iDznPB pushed fix

**Comment by iDznPB** [comment]
looks good, thanks
