### ISSUE TITLE
[BUG] Models vanishing

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#222]
**Describe the bug**
I raised this before but closed as I thought it was user error.

**To Reproduce/Line of code causing issue**
1. Cache object
2. draw model
3. see model vanish and nextpoint go null -1 -1

**Expected behavior**
Not keep vanishing and returning broken values. Causing a lot of missclicks

**Screenshots**
https://gyazo.com/6eeacefb0b45d5d2ddf00483feeb1de1

**Additional context**
Because the model is dead, I assume it tries to use the base point (tile) to generate a click point and in turn just generates a load of shite when interacting.

**Comment by iDznPB** [comment]
On further investigation, I think the entire cached object is breaking, thus no model, no next point, also has no name, no ID etc
The interactive object debug shows correctly and doesn't vanish, but the following code returns broken values.

```
GameObject obj = GameObject.getNil();
@Override
	public void poll() {
		if(obj==GameObject.getNil()) {
			obj = Objects.stream().name("Ladder").nearest().first(); //at mother load mine or door somewhere
		}
	}
	
	
@Subscribe
	public void onRender(RenderEvent renderEvent) {
		Rendering.setScale(1.0f);
		Rendering.setColor(Color.argb(255, 227,28,121));
		obj.model().draw(obj.localX(), obj.localY());
         }
```

**Comment by constt** [comment]
@iDznPB That's possible because the obj may move to a new place in memory, made some model changes though

**Comment by iDznPB** [comment]
@constt not sure if this is from the recent model changes but model orientation seems inconsistent.

Sometimes when displaying the object model, it's correct, then the next time I stream it and display it, it's wrong.
![image](https://user-images.githubusercontent.com/34009165/220073767-cbc4093d-4e43-47f7-b432-79d0e810590d.png)

**Comment by constt** [comment]
@iDznPB fixed orientation issue

**Comment by iDznPB** [comment]
Can confirm orientation fixed, closing as complete!
