### ISSUE TITLE
[BUG] Render only interacting delays and interaction issues (dev build)

### ISSUE THREAD

**Issue by ghost** [powbot/issues#224]
**Describe the bug**
Since about a week ago, I've noticed a couple of issues when the config is enabled. 

It seems that when an API call to interact with an object/npc is made, it likes skip the method entirely because the model hasn't loaded in yet. This wasn't an issue just after its release and only has started to happen recently.

There is also what seems like an issue with loading in objects, sometimes this process can take upwards of 3-ish seconds when before it would just interact as if the config was off. This also seems to look like interaction calls need to happen twice, once to load in the model, and again to actually interact

https://user-images.githubusercontent.com/64224090/220888120-afcfdf07-51ee-4de6-b649-e0d79a715294.mp4

^ what it does with the config enabled (broken)

https://user-images.githubusercontent.com/64224090/220888314-e9b68e5b-6243-453c-a2db-6201141e515c.mp4

^ What it does with the config disabled (correct)

**Comment by constt** [comment]
made an improvement @Protoprize

**Comment by ghost** [comment]
Seems to be a lot better now :)
