### ISSUE TITLE
[BUG] .within(area) ignoring outer tiles

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#226]
**Describe the bug**
easier to see from the screenshots but the first one where the model is not highlighted IS inside the area, or intersecting, whatever. It's not being found in the stream. Whereas the second one IS highlighted and in turn being found inside my stream.

**To Reproduce/Line of code causing issue**
```
for(GroundItem mark:GroundItems.stream().name("Mark of grace").within(currentArea)){
       mmark. Model).draw(mark.localX(), mark.localY());
}
for(Tile tile: currentArea.getTiles()){
       Rendering.drawPolygon(tile. Matrix().bounds());
}
```

**Expected behavior**
Include the mark on the edge of the area

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/221301566-6800ab9c-13e9-406e-93b3-3f94280cadb7.png)
![image](https://user-images.githubusercontent.com/34009165/221301583-94c8aa39-7c5f-40ef-8d1c-def528fd6821.png)

**Comment by constt** [comment]
@iDznPB pushed fix

**Comment by iDznPB** [comment]
Closed as completed, thank you!
