### ISSUE TITLE
XP Trackers not working in paint [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#26]
**Describe the bug**
Paint does not track XP for skills

**To Reproduce/Line of code causing issue**

```
    @Override
    public void onStart() {
        addPaint(new PaintBuilder()
                .trackSkill(Skill.Fishing)
                .build());
    }
```

**Comment by constt** [comment]
@Protoprize Can you check to see if getting skill levels & experiences works please

**Comment by ghost** [comment]
@constt Yep, both XP and Levels are working fine on their own.

**Comment by constt** [comment]
@Protoprize Resolved, please confirm and close

**Comment by ghost** [comment]
Works
