### ISSUE TITLE
Models/hulls missing causing most scripts to misclick 99% of the time [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#27]
**Describe the bug**
Whenever trying to interact with anything, most of the time it will not be able to click the 'interactable' part of the model.

**To Reproduce/Line of code causing issue**
Interacting with objects/npcs

**Comment by constt** [comment]
@Protoprize Just pushed models for :

Objects
Npcs
Ground Items

Note: The orientation on them is wrong for most, can be controlled via:

``` fun customModelOrientation(orientation: Int)```

Lets keep all feedback in here and if someone can work out orientation hit me up

**Comment by constt** [comment]
@Protoprize Fixed bad orientation and animation, please test

**Comment by iDznPB** [comment]
> @Protoprize Fixed bad orientation and animation, please test

This is fixed and can be closed
