### ISSUE TITLE
Elevation breaks npc/object locations [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#31]
**Describe the bug**
Very apparent in barbarian outpost (Barb fishing area), NPCs and Objects are in the wrong places, causing broken interactions

**Screenshots**
![image](https://user-images.githubusercontent.com/64224090/185718500-555ef071-81dc-459c-9f92-cec24bfb002a.png)

https://user-images.githubusercontent.com/64224090/185718506-8ee22637-eb9e-40e2-9ccc-f013ca400a4c.mp4

**Comment by constt** [comment]
[Image](https://i.imgur.com/ApHVCJW.png)
@Protoprize  could you get me tile height/landscape meta on this tile using a desktop client please?
