### ISSUE TITLE
Inventory items have missing information [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#33]
**Describe the bug**
Selected Item debug not reporting correct item info (only name) + wrong Item IDs being reported

**Screenshots**

![Screenshot 2022-08-21 at 21 07 36](https://user-images.githubusercontent.com/64224090/185808973-4ce9dee4-03cc-4208-847d-9dc38f1385f0.png)
![Screenshot 2022-08-21 at 21 09 39](https://user-images.githubusercontent.com/64224090/185809042-4e5fcb7a-9cce-4a57-b544-60e93a61fc10.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: Device
 - OS: Android 12
 - Arch: ARM64

**Comment by constt** [comment]
@Protoprize please test

**Comment by ghost** [comment]
Fixed
