### ISSUE TITLE
[BUG] UI not visible/bot not bootstrapping correctly on certain devices.

### ISSUE THREAD

**Issue by benpoulson** [powbot/issues#35]
**Describe the bug**
UI not visible/bot not bootstrapping correctly on certain devices. 

I can see everything bootstrapping correctly, the instance ID is set, the port 61666 gets listened to, but I think something is failing somewhere, as the login button still sends you to the webview.

**To Reproduce/Line of code causing issue**
1. Load up the app
2. Nothing

**Expected behavior**
UI to be visible

**Screenshots**

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/1797843/185913715-68ba3dd2-28c3-4583-b337-e518c113286e.png">

**Logs**
[iTerm2 Session 22 Aug 2022 at 12:32:09 pm.txt](https://github.com/powbot/issues/files/9393938/iTerm2.Session.22.Aug.2022.at.12.32.09.pm.txt)

**Emulator or device (please complete the following information):**
 - Device/Emulator: Device
 - OS: `Android 10`
 - Arch: `Linux localhost 4.9.170 #1 SMP PREEMPT Tue Aug 16 20:40:35 BST 2022 armv8l`
 - Processor: `H313`
 - GPU: `Mali-G31 MP2`
 - ro.vendor.build.version.release = 10
 - ro.vendor.build.version.sdk = 29
 - ro.vendor.product.cpu.abilist = armeabi-v7a,armeabi
 - ro.vendor.product.cpu.abilist32 = armeabi-v7a,armeabi
 - ro.vendor.product.cpu.abilist64 = 

**Additional context**

**Comment by benpoulson** [comment]
Also, same issue on Android 10 stock, 10-AOSP and 11-AOSP. So it's not some wild OS change I've made.

**Comment by constt** [comment]
This is likely because of 32bit arm

**Comment by Krulvis** [comment]
Hijacking this but I have a problem where the UI disappears when device (OnePlus N10 5G, arm64-v8a) goes to black screen and is turned on again. RS opens but bot UI is gone. No errors :(

**Comment by benpoulson** [comment]
Confirmed this is due to 32bit ARM not being supported at this time.
