### ISSUE TITLE
Times in paint not correct

### ISSUE THREAD

**Issue by okazakikun** [powbot/issues#36]
**Describe the bug**
Time based stats on paint not displaying/calculating correctly, runtime showing -12:-49:-16

**To Reproduce/Line of code causing issue**
1. run script
2. look at paint

**Emulator or device (please complete the following information):**
 - Device/Emulator: bluestacks 5
 - OS: Android Pie
 - Arch: ARM64

![image](https://user-images.githubusercontent.com/26844787/185926222-294adbb2-4e72-4952-8c19-71c7f79b30ba.png)

Level and xp gained are correct

**Comment by constt** [comment]
Fixed in next build

**Comment by okazakikun** [comment]
Confirmed working as intended.
