### ISSUE TITLE
[BUG] Missing Agility Objects

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#38]
**Describe the bug**
Object is not visible on the debug and does not return in the stream
Screenshot one is at the varrock general store as per screenshot below (Rough wall)
Tile(x=3221, y=3414, floor=0, localX=45, localY=54)

Also the one in draynor as per second screenshot

**To Reproduce/Line of code causing issue**
```
Objects.stream().within(tile as per above, 4).nearest(tile as per above).action("Climb").name("Rough wall")
```

**Expected behavior**
Above code is empty when it should have the rough wall.

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/186238830-a2154e00-0f20-4554-946f-4707c013a54f.png)
![image](https://user-images.githubusercontent.com/34009165/186239493-4a287fb7-297b-4a22-ae00-fbcbcca44cbd.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB please test

**Comment by iDznPB** [comment]
Can confirm working.
![image](https://user-images.githubusercontent.com/34009165/187094302-e713c9cd-3d99-4736-a114-e5d60003ab58.png)
