### ISSUE TITLE
[BUG] Bank/Shops Inventory Not Updating

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#39]
**Describe the bug**
When buying items from the shop, the inventory doesn't update to reflect the new items, in turn things like inventory.isfull() return false because the items don't exist until the shop window is closed.

EDIT:On further inspection, this is anything which doesn't use the standard inventory container, i.e. banks too (screenshot added below)

**To Reproduce/Line of code causing issue**
1. turn on inventory debug
2. buy an item from a shop
3. see wonky inventory debug

**Expected behavior**
Assuming that the inventory widget changes when the shop is open; for this separate widget to also update Inventory stream.

**Screenshots**
![HD-Player_cu81EpipgQ](https://user-images.githubusercontent.com/34009165/186846323-03efaf70-68bf-4df7-b0a4-772e1bfccd0d.gif)
![image](https://user-images.githubusercontent.com/34009165/186848006-2179d2b3-8949-40ab-bb80-fbb937d4d4a8.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: Pie64
 - Arch: ARM

**Comment by iDznPB** [comment]
BANK_INVENTORY_GROUP_ID = 15
BANK_INVENTORY_ITEM_CONTAINER = 3

DEPOSIT_BOX_INVENTORY_GROUP_ID = 192,
DEPOSIT_BOX_INVENTORY_ITEMS_CONTAINER = 2,

SMITHING_INVENTORY_GROUP_ID = 312,
SMITHING_INVENTORY_ITEMS_CONTAINER = 0,

GUIDE_PRICES_INVENTORY_GROUP_ID = 238,
GUIDE_PRICES_INVENTORY_ITEMS_CONTAINER = 0,

SHOP_INVENTORY_ITEMS_GROUP_ID = 301,
SHOP_INVENTORY_ITEMS_CONTAINER = 0,

SEED_VAULT_INVENTORY_GROUP_ID = 630,
SEED_VAULT_INVENTORY_ITEMS_CONTAINER = 1,

EQUIPMENT_INVENTORY_GROUP_ID = 85,
EQUIPMENT_INVENTORY_ITEMS_CONTAINER = 0,
[10:09]
Think that's all?

**Comment by constt** [comment]
@iDznPB Fixed widget #isHidden which fixes this, please test

**Comment by iDznPB** [comment]
> @iDznPB Fixed widget #isHidden which fixes this, please test

Can confirm this is fixed.
