### ISSUE TITLE
Script Selector Table [BUG]

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#4]
**Describe the bug**
Minor bug, the table is a little wonky

**To Reproduce/Line of code causing issue**
1. open script selector

**Expected behavior**
A non wonky table

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/184611377-d96215a1-b6d9-4cd8-8637-77fcaaaa3604.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
This has been resolved.
