### ISSUE TITLE
[BUG] Scrolling/world hopping

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#40]
**Describe the bug**
Unable to scroll the world hop panel.

**To Reproduce/Line of code causing issue**
```
world.hop(); // where world is not visible on screen
```

**Expected behavior**
Scroll to world and hop

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Additional context**
Do action hopping would be so sexy.
The RL world hopper would be a good place to start since you can double click a world in the plugin and it quick hops to that world without the world being visible in the list.
https://github.com/runelite/runelite/blob/3c185256253a27d11a6c6630002d16a9fa82c71a/runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java

**Comment by PTYB** [comment]
Happy to close this and spin off another ticket for the enhancement?

**Comment by iDznPB** [comment]
> Happy to close this and spin off another ticket for the enhancement?

Go for it
