### ISSUE TITLE
Missing/Incorrect/Phantom objects [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#42]
**Describe the bug**
There are instances of missing objects and incorrect details for them. Have only come across this in the Abyss area and runecrafting altars.

**Screenshots**
![image](https://user-images.githubusercontent.com/64224090/187286473-3c04cda4-5f1a-4128-bcf2-07df20c59d4d.png)
![image](https://user-images.githubusercontent.com/64224090/187286490-9382889e-a284-4fa1-a94c-f6cf91224aa6.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: Device
 - OS: Android 12
 - Arch: ARM64

**Comment by constt** [comment]
Mysterious ruins should be fixed, please test and update @Protoprize

**Comment by iDznPB** [comment]
Dynamic: 350
UID: 9007245096526757
basic: 1435263909
("Boxes" - Should be Large guardian remains)
![image](https://user-images.githubusercontent.com/34009165/187781596-3b2cc6e0-8cb4-4c95-a2c6-4cf2fa7ddebb.png)


Dynamic: 2
UID: 13510844730188746
basic: 1436050378
("Cave entrance" - Should be rubble)
![image](https://user-images.githubusercontent.com/34009165/187781548-aaa2ec66-722f-4a54-8aef-6b7c5a4b7044.png)
also a second rubble to climb back up:
![image](https://user-images.githubusercontent.com/34009165/187781783-d96512c9-1fdf-483b-b0a2-484e57d11850.png)

**Comment by constt** [comment]
@iDznPB @Protoprize 20mins then should be fixed please confirm

**Comment by iDznPB** [comment]
Closed for now, looks fixed from everyones testing last night.
