### ISSUE TITLE
[BUG] Camera pitch and yaw change

### ISSUE THREAD

**Issue by nschaa** [powbot/issues#43]
**Describe the bug**
Camera can recognize if it is in the correct pitch, yaw, or zoom but actually changing the Pitch or Yaw seems to be bugged, mouse just drags across screen.

**To Reproduce/Line of code causing issue**

`Camera.pitch(int)  and 
Camera.turnTo(int,int);
`

**Expected behavior:**
Turn Camera and pitch accordingly.

**Emulator or device (please complete the following information):**
Device/Emulator: BS
OS: P64
Arch: ARM

**Comment by iDznPB** [comment]
[1920x1080.txt](https://github.com/powbot/issues/files/9473123/1920x1080.txt)
[1600x900.txt](https://github.com/powbot/issues/files/9473125/1600x900.txt)
[1280x720.txt](https://github.com/powbot/issues/files/9473128/1280x720.txt)

**Comment by constt** [comment]
Thanks @iDznPB , should be better in the next release, it's not 100% but you know it works

**Comment by nschaa** [comment]
Thanks @constt , Camera can rotate now but it is still unreliable. It is prone to going back to where it just drags the mouse across the screen when Camera is max zoomed out and trigger a Camera.turnTo() method. 

Is there any chance you could take another look for a more stable improvement?

**Comment by nschaa** [comment]
What triggers the Mouse being dragged across the screen for me:

`Camera.turnTo(Random.nextInt(190,210));`

But it seems any Camera rotation above 190 can cause this issue still.

**Comment by constt** [comment]
@nschaa Please try now

**Comment by nschaa** [comment]
@constt  Camera.turnTo() works a lot better now, thanks!

**Comment by iDznPB** [comment]
Closed as per above
