### ISSUE TITLE
[BUG] Camera.getZoom() incorrect value

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#44]
**Describe the bug**
Zoom returns 16-231; it scales correctly and always returns consistently, just not 0-100 like it used to be.

**Expected behavior**
0-100 as % iirc

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB fixed in next build

**Comment by iDznPB** [comment]
Resolved
