### ISSUE TITLE
Input.drag() drags too slowly, Camera movements also do not work

### ISSUE THREAD

**Issue by TacticalMullet** [powbot/issues#46]
**Describe the bug**
`Input.drag()` drags too slowly, causing it to register as a press and hold tap instead of drag. This also appears to impact `Camera.turnTo()`, which exhibits similar behavior.
display settings:1600x900 240 dpi

**Comment by constt** [comment]
@TacticalMullet Should be resolved, please test

**Comment by ghost** [comment]
@constt works for short distances, but if you need to turn more than around 90 degrees, it will just make a dragging motion across the screen but won't drag

**Comment by TacticalMullet** [comment]
As far as I can tell from my scripts, this is fixed. I haven't been able to reproduce the issue mentioned by @Protoprize , maybe has something to do with dpi settings?

**Comment by iDznPB** [comment]
#43 was related and confirmed resolved, closing as per original issue being fixed.
