### ISSUE TITLE
[BUG] Inventory locations bugged

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#49]
**Describe the bug**
Inventory Items appear on the wrong side of the game, behind the magic panel when trying to enchant jewellery

**To Reproduce/Line of code causing issue**
1. turn on inventory debug
2. have inventory full with runes for jewellery enchant and jewellery
3. start powmagic select jewellery enchanting
4. watch the script click the spell and then flick to the inventory, it then doesn't update for about 60 seconds or so

**Expected behavior**
Items to be on the other side..

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/187688900-ce0a7ea5-d3c9-490e-a0f8-384a6ba44a59.png)

**Additional context**
Yes I cleared my cache, restarted and the same thing happened.

**Comment by constt** [comment]
Have pushed a change which may fix @iDznPB

**Comment by iDznPB** [comment]
@constt 
it was working for the first like maybe 6 or 7 spell casts, then it started doing this

https://user-images.githubusercontent.com/34009165/188269505-bea53d11-31fc-4c66-a31c-5f35df9ec98b.mp4

**Comment by constt** [comment]
@iDznPB Should be fixd now

**Comment by iDznPB** [comment]
Resolved
