### ISSUE TITLE
[BUG] Prayer.prayerPoints() returns -1

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#51]
**Describe the bug**
Prayer.prayerPoints() returns -1

**Expected behavior**
Return the actual prayer points.
If hook is borked, could use the widgets 
Widgets.widget(160).component(20).text()

**Comment by constt** [comment]
Fixed in next looks like they moved widgets again

**Comment by iDznPB** [comment]
> Fixed in next looks like they moved widgets again

@constt cleared cache, re-installed but still returning -1

**Comment by iDznPB** [comment]
New install fixed
