### ISSUE TITLE
[BUG] AutoLogin does not work 

### ISSUE THREAD

**Issue by ghost** [powbot/issues#52]
**Describe the bug**
AutoLogin gets stuck on typing in account details and clicking login when account details are already saved in the game.

**Comment by 7upSprite** [comment]
To add onto this-

Pow App Crashes if already logged in before and the account is cached on login screen as in the video link. Error log below.

[https://imgur.com/a/hRxbDVJ](url)

```
[INFO] known ign is [null], saved is [null]
[INFO] Handling sign out, we don't know the user
[INFO] Handling try again button```
```
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: End of stream or IOException
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:660)
	at org.powbot.mobile.service.ScriptUploader.uploadAndStart(ScriptUploader.kt:83)
	at org.powbot.mobile.service.ScriptUploader.uploadAndStart(ScriptUploader.kt:79)
	at scripts.7up.Main.main(Main.java:73)```

^ Line 73 is ```new ScriptUploader().uploadAndStart("7up", "1", "127.0.0.1:5555", true, false);```
^ To add: In the account manager, the only account in there has the nickname 1 which is defined after my script name 7up.

**Comment by constt** [comment]
@Protoprize please test

**Comment by iDznPB** [comment]
This logged me in with an account already signed in for example a 6 hour log scenario @Protoprize

**Comment by iDznPB** [comment]
However this only works when NOT selecting an account

**Comment by iDznPB** [comment]
![image](https://user-images.githubusercontent.com/34009165/193521552-cb3987ea-c772-4c83-9e2a-d6a275d04763.png)
from Litago on discord

**Comment by ghost** [comment]
Has been working fine for me the last month, good to close I think if others agree :)
