### ISSUE TITLE
[BUG] OkHttp not supported in Pow SDK

### ISSUE THREAD

**Issue by Nickert1337** [powbot/issues#53]
**Describe the bug**
OkHttp used to be included into the client sdk. I used this http wrapper do check which user is running the scripts, besides that no other info was logged at that moment.

In the future it would have been used to authenticate premium users.

**To Reproduce/Line of code causing issue**
1. Use OkHttpClient in your code.
2. Try to compile.
3. Not working

**Logs**
`[ERROR] [ERROR] /tmp/32b7be20-ef43-488d-b594-8eb18e25d651/src/main/java/frameworks/OelWebApi.java:[28,19] cannot find symbol
[ERROR]   symbol:   class OkHttpClient
[ERROR]   location: class oelaboela.scripts.frameworks.OelWebApi
[ERROR] [ERROR] /tmp/32b7be20-ef43-488d-b594-8eb18e25d651/src/main/java/frameworks/OelWebApi.java:[3,1] package com.squareup.okhttp does not exist`

**Comment by constt** [comment]
should be fixed, you'll still need to include it locally when developing but the build bot should work

**Comment by Nickert1337** [comment]
The script seems to build again:
![image](https://user-images.githubusercontent.com/98966743/188413983-c94b9226-880a-43d0-9cb4-b963061e4bdb.png)

Thanks! Closing this issue.
