### ISSUE TITLE
[BUG] Disable Input on Client

### ISSUE THREAD

**Issue by 7upSprite** [powbot/issues#54]
**Describe the bug**
When you click the disable input button and turn it red, you are still able to click and ur mouse clicks go through to the game. Disable input button not working

**Emulator or device (please complete the following information):**
 - Device/Emulator:  Bluestacks
 - OS: [Android Pie] - Default
 - Arch: [e.g. ARM64] - Default

**Additional context**
![8EV1LyoZvG](https://user-images.githubusercontent.com/48745305/187809447-9e19cc02-568b-42c6-a7c6-e6329b56b9b4.gif)

**Comment by constt** [comment]
fixed in next, please test

**Comment by benpoulson** [comment]
Confirmed working.

**Comment by 7upSprite** [comment]
![image](https://user-images.githubusercontent.com/48745305/188339873-302b282d-d7e3-4ba4-8428-094e124984f2.png)

Will wait for confirmation from Proto as well.

**Comment by iDznPB** [comment]
With multiple confirmations of this being fixed, will close this.
