### ISSUE TITLE
[BUG] Orientation missing for wall objects.

### ISSUE THREAD

**Issue by ghost** [powbot/issues#56]
**Describe the bug**
Wall objects are missing orientation

**To Reproduce/Line of code causing issue**

    @Subscribe
    fun onRender(renderEvent: RenderEvent?) {
        setScale(1.0f)
        var obj = Objects.stream().name("Nature rift").nearest().first()
        if (obj.valid()) {
            obj.model()!!.draw(obj.localX(), obj.localY())
        } 
    }

**Screenshots**

![Screenshot 2022-09-01 at 08 03 18](https://user-images.githubusercontent.com/64224090/187852750-853c4ee0-5059-4772-a9ee-3d48e6aa3b82.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: Device
 - OS: Android 12
 - Arch: ARM64

**Comment by iDznPB** [comment]
Noticed this too on some agility starting objects since they're all climbing up walls etc

**Comment by Nickert1337** [comment]
Noticed this on BlastMining objects, fixing this issue should fix that script almost entirely.

**Comment by constt** [comment]
fixed
