### ISSUE TITLE
[BUG] Incorrect long taps

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#57]
**Describe the bug**
Game.tab(Game.Tab.MAGIC);
menu taps the tab, doesn't select Magic from the menu.

Movement.step() does the same too

**To Reproduce/Line of code causing issue**

```
Game.tab(Game.Tab.MAGIC);
```

**Expected behavior**
Open specified tab. However with single tap enabled, it shouldn't open the menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/34009165/188105127-c2b384a5-b9c8-4ba2-a126-51e30a5f2f05.png)

**Comment by Nickert1337** [comment]
I'm experiencing the same:

http://bwaan.nl/img/AnyDesk_vitUAoAb2E.gif

**Comment by constt** [comment]
Fixed in next

**Comment by iDznPB** [comment]
Confirmed working <3
