### ISSUE TITLE
[BUG] Ground items not showing up on agility course

### ISSUE THREAD

**Issue by okazakikun** [powbot/issues#59]
**Describe the bug**
Ground items do not display when on a rooftop agility course, marks of grace are un-grabbable because of this

**To Reproduce/Line of code causing issue**
1.Go to rooftop agility ( i tested ardy)
2. drop item/mark spawns
3. no ground items show

**Expected behavior**
Ground items to display

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks 5
 - OS: Android Pie
 - Arch: ARM64

**Additional context**
Tested upstairs in houses and ground objects show correctly, Ardy roofs "floor" value is 3, may be relevant

**Comment by iDznPB** [comment]
Thanks for raising this, was going to do it today, I raised a ground items issue previously but since constt is non members he tested on the ground floor and was fine, but looks like it's isolated to rooftops somehow

**Comment by constt** [comment]
fixed in next

**Comment by iDznPB** [comment]
Resolved
