### ISSUE TITLE
Settings do not persist in the settings pane [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#6]
**Describe the bug**

The settings pane does not save the settings on restart

**To Reproduce/Line of code causing issue**

Disable/enable any, and restart client. They will be back to default

**Expected behavior**
Settings get saved 

**Screenshots**
This settings pane
![image](https://user-images.githubusercontent.com/64224090/184614612-641e22e4-a323-4188-bde5-c8af671f1928.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by constt** [comment]
Resolved, please test

**Comment by MichalTDev** [comment]
Resolved

**Comment by ghost** [comment]
Working
