### ISSUE TITLE
[BUG] Movement.running(boolean) doesn't turn on or off run

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#60]
**Describe the bug**
Not turning on or off run

**To Reproduce/Line of code causing issue**

```
Movement.running(boolean)
```

**Expected behavior**
Turn on or off run

**Additional context**
160.29
![image](https://user-images.githubusercontent.com/34009165/188269871-ad61b574-ab4c-43c8-b3d4-888f239f4404.png)

**Comment by benpoulson** [comment]
I would assume it's a widget mixup. For me it's trying to interact with my quick-prayer icon.

**Comment by iDznPB** [comment]
mine doesn't' do anything, but yeah most likely widgets

**Comment by Nickert1337** [comment]
Can confirm, reading the running state works but enable/disable doesn't work.

**Comment by constt** [comment]
should be fixed in next

**Comment by benpoulson** [comment]
Working for me.

**Comment by iDznPB** [comment]
Closed as per above
