### ISSUE TITLE
[BUG] Quests.INSTANCE.getCompletedQuests() returns nothing

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#61]
**Describe the bug**
Quests.INSTANCE.getCompletedQuests() doesn't return any of the completed quests, assuming widgets have changed.

![image](https://user-images.githubusercontent.com/34009165/188270034-ce4efb11-ad49-4067-8e3d-0db6030f32c7.png)
399.7.X

**Comment by constt** [comment]
fixed in next

**Comment by iDznPB** [comment]
resolved
