### ISSUE TITLE
[BUG] Misclicking on objects/npcs 

### ISSUE THREAD

**Issue by ghost** [powbot/issues#64]
**Describe the bug**
The client seems to misclick a lot on objects/npcs. Same when statinary and not. 
It looks like it clicks outside of the bounds of the model, downscaling does not change the are that the client will interact with (but model does get downsized when rendering it)

**Emulator or device (please complete the following information):**
 - Device/Emulator: All
 - OS: Android 9/12

**Comment by constt** [comment]
@Protoprize some videos would be good here

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/64224090/188317120-f7074479-ebee-42a3-b3aa-b9cf6c276f3b.mp4

@constt  you can see when it interacts with the altar, it seems to tap outside of it's model a couple of times

**Comment by constt** [comment]
@Protoprize could you draw the model/hull

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/64224090/189547389-8a1a45e9-5251-49f2-9594-f5cc3e6e430b.png)
![image](https://user-images.githubusercontent.com/64224090/189547397-dddcb5dd-91b3-4e7e-b010-c0d8ad61f137.png)
@constt
