### ISSUE TITLE
[BUG] priv = false/true in script manifest not applying 

### ISSUE THREAD

**Issue by ghost** [powbot/issues#65]
**Describe the bug**
After setting a script to be private, you can't un-private it

```
@ScriptManifest(name = "PP Abyss crafter", description = "Start in edgeville with glories, lobsters and essence in bank", version = "3.3", category = ScriptCategory.Runecrafting, scriptId = "[REDACTED]", singleTapRequired = true, priv = false)
```

![image](https://user-images.githubusercontent.com/64224090/188282143-9884a157-c795-41d9-946e-9be585325deb.png)

**Comment by Nickert1337** [comment]
Might not be completely related but I pushed OelMagicTrainingArena with priv=false and it still does not show up. I had the script 'disabled' before the scripts web-page went down.

**Comment by constt** [comment]
should now work correctly

**Comment by Nickert1337** [comment]
I pushed my script with the priv=false manifest but it still isn't available to the public. When executing the .script command in the bot-spam channel it shows that the script isn't available:

`OelMagicTrainingArena - [5dd40312-b7ef-41b8-8bad-034e6bb27c21] (NOT_AVAILABLE)`

I have a feeling this might be a seperate issue to a script being privated or not_available but that's up to @constt I guess :)

**Comment by constt** [comment]
@Nickert1337 try now
