### ISSUE TITLE
[BUG] Widget screenPoints not updating after scroll

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#66]
**Describe the bug**
When scrolling within an interface (worldhopper, in this instance), the screenPoint of the target widget is not changing despite a scroll being executed and the position of the widget updating visually on the screen.  I am calling the following code between each scroll attempt, so it should be streaming for a new object with each call, however the new object returns the same screenPoint as it previously did.
```
        Component viewportComponent = Components.stream(69).id(15).viewable().first();
        Component worldComponent = Components.stream(69, 16).id(worldId).first();
```

**To Reproduce/Line of code causing issue**
1. Run the code below in a loop with the WorldHopper open, and manually scroll in the worldhopper screen.  It will return the same screenPoint even though it has moved.
`System.out.println(Components.stream(69,16).id(308).first().screenPoint());`

**Expected behavior**
The point should update to the new position on the screen

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Pie
 - Arch: 64-bit

**Comment by constt** [comment]
@5Henveru2 Please try now I made some changes

**Comment by 5Henveru2** [comment]
Seems like it's working, however there is a significant delay before it recognizes the new position.  I have set a timeout of 1500 ms, sometimes it hits the timeout and hasn't detected the new position, other times it recognizes the change within 300-600ms.  Not sure if we can improve that, for something like worldhopper scrolling it's not that important, but for other in-game mechanics it may be problematic.

**Comment by rvbiljouw** [comment]
the delay should be reduced to sub-second, please give it a go on the latest build

**Comment by 5Henveru2** [comment]
Can confirm that it was looking better the last time I was testing things.
