### ISSUE TITLE
[BUG] Spot animation not resetting to 0 or -1 when action is performed through a script

### ISSUE THREAD

**Issue by xpr0legendx** [powbot/issues#67]
**Describe the bug**
In the previous client the spot animation was -1, similar to animation that is -1. When performing an action that makes the player do a spot animation manually, the spot animation will reset back to 0 after its done. When doing the same action through a script the spot animation will not reset to 0 (in the case of getting stunned when thieving the spot animation remains at 56).

**To Reproduce/Line of code causing issue**
```
val npc = Npcs.stream().name("Man").first();
npc.interact("Pickpocket")
```

**Expected behavior**
Spot animation should reset back to its original value 0 after the spot animation is done (or preferably have the original value be set to -1 as spot animations start with 0)

**Screenshots**
https://ibb.co/JRdR1nf
https://ibb.co/vB7X1cm

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: [Android Pie]
 - Arch: [ARM64]

**Comment by constt** [comment]
@xpr0legendx does this sstill happen?

**Comment by xpr0legendx** [comment]
> @xpr0legendx does this sstill happen?

Yes, this still happens. However, now it won't reset back to 0 even when manually performing the action.

**Comment by constt** [comment]
@xpr0legendx images not working please upload a video

**Comment by Nickert1337** [comment]
It's still not resetting:
![image](https://user-images.githubusercontent.com/98966743/191943742-de3bac09-2330-4978-8405-ae145093da08.png)

**Comment by Nickert1337** [comment]
Still not resetting as of today:
![image](https://user-images.githubusercontent.com/98966743/193079318-64e16b14-5fcd-4652-a28c-0193a4899861.png)

**Comment by constt** [comment]
@Nickert1337 @xpr0legendx please test

**Comment by iDznPB** [comment]
Working beautifully, will close thanks!

> @Nickert1337 @xpr0legendx please test
