### ISSUE TITLE
[BUG] Players.local.healthpercent() returning -1 on some devices

### ISSUE THREAD

**Issue by ghost** [powbot/issues#68]
**Describe the bug**
I've noticed that on one of my devices, the function returns -1. The script itself works as long as I don't call that function.
Its fine on bluestacks, broken on my phone. Not sure where I can get any other logs to help, but let me know if there is anything 

**Emulator or device (please complete the following information):**
 - Device/Emulator: Device
 - OS: Android 12L
 - Arch: ARM64

**Comment by benpoulson** [comment]
Is it the same thing for `Skills.level(Skill.Hitpoints.getIndex())` ?

**Comment by iDznPB** [comment]
> Is it the same thing for `Skills.level(Skill.Hitpoints.getIndex())` ?

This does work, litago has said issue on his device and I added that check and it works for him

**Comment by rvbiljouw** [comment]
might be fixed in latest build, pls test

**Comment by ghost** [comment]
@rvbiljouw  Still having this issue on the latest client. Now it's the same on every device/emulator

**Comment by constt** [comment]
@Protoprize please test in 20

**Comment by ghost** [comment]
@constt  still reporting -1

**Comment by constt** [comment]
@Protoprize give it a go now

**Comment by ghost** [comment]
Fixed :)
