### ISSUE TITLE
[BUG] Client crash upon relaunch

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#69]
**Describe the bug**
Sometimes, the client is unable to launch without crashing, and needs to be reinstalled.

**To Reproduce/Line of code causing issue**
Not sure how to reproduce.

**Logs**
https://hastebin.com/razihataxi.apache

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Pie
 - Arch: 64bit

**Additional context**

**Comment by constt** [comment]
@5Henveru2 Known bug currently, try clearing the app cache instead next time and force stopping it.
