### ISSUE TITLE
Single tap returns False when enabled [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#7]
**Describe the bug**
Single tap debug returns false when enabled
It detects what type of function key you've got set correctly (screenshots below)

**To Reproduce/Line of code causing issue**
Enable single tap mode

**Expected behavior**
Single tap mode == true

**Screenshots**

![image](https://user-images.githubusercontent.com/64224090/184615300-24ec4644-5d3c-42a4-ae59-f05afc49c83e.png)
![image](https://user-images.githubusercontent.com/64224090/184615406-3e8648dd-27b8-4ce5-84f5-ca981c9fe818.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by constt** [comment]
@Protoprize can you see if this is resolved pelase

**Comment by ghost** [comment]
@constt Works now :)
