### ISSUE TITLE
[BUG] Input.sendln unreliable / doesn't work

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#70]
**Describe the bug**
I can't get Input.sendln to type anything reliably.  It does occasionally work but I don't know what the trigger is.

**To Reproduce/Line of code causing issue**
Open bank, choose withdraw-x on an item so that the withdraw menu is open, and then run this code:
```
Input.sendln("200000");
```

**Expected behavior**
It should type in the passed argument and press return/enter.

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: 64 bit

**Comment by benpoulson** [comment]
Same issue as #45

**Comment by iDznPB** [comment]
As per above, being resolved on #45 will close this for now.
