### ISSUE TITLE
[BUG] Under Canifis

### ISSUE THREAD

**Issue by Karasandra** [powbot/issues#72]
Area under Canifis is broken. Probably a easy fix. But ya.

https://user-images.githubusercontent.com/7262120/188334427-e2634880-3f1e-4ce3-8d47-23619ea0fc66.mp4

![Capture](https://user-images.githubusercontent.com/7262120/188334447-6b9e0e82-439e-456d-84c7-57afbde0aa1f.PNG)

 - Device/Emulator: Bluestacks
 - OS: P64 OnePlus3T
 - Arch: ARM

**Comment by constt** [comment]
@Karasandra does this still happen?

**Comment by Karasandra** [comment]
Yes still happening. @constt

**Comment by Nickert1337** [comment]
This also happens in some other way at the blast mine:
![image](https://user-images.githubusercontent.com/98966743/191362986-17c40392-6027-4986-b09f-095ad58e3a84.png)

![image](https://user-images.githubusercontent.com/98966743/191363043-5fd4f9c4-9ac7-4cd0-a5b1-726404d24987.png)

**Comment by constt** [comment]
@Nickert1337 @Karasandra please try in 20

**Comment by iDznPB** [comment]
@Nickert1337 @Karasandra 
any update on this?

**Comment by Nickert1337** [comment]
I haven't got membs anymore unfortunately.
