### ISSUE TITLE
[BUG] Equipment caching while banking sporadically breaks after extended run time (hour+)

### ISSUE THREAD

**Issue by ghost** [powbot/issues#73]
**Describe the bug**
Equipment caching becomes not avaliable randomly after around an hour of run time. Specifically if you're checking eq while bank interace is open is when this is apparent. 

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS5
 - OS: Android 9
 - Arch: ARM64

**Comment by constt** [comment]
@Protoprize equip/inv caching wasn't working at all, should be good now.

**Comment by ghost** [comment]
Working :)
