### ISSUE TITLE
[BUG]Inventory interacting randomly breaks

### ISSUE THREAD

**Issue by Nickert1337** [powbot/issues#74]
**Describe the bug**
At some random point when the script starts interacting with the chat bar (the one at the top of your screen) when it tries to interact with a inventory item. Restarting the game/clearing cache/recompiling the script won't work. Reinstalling the APK seems to work though.

**To Reproduce/Line of code causing issue**
1. Start any script that does inventory interacting as first action.
2. Start/stop it a few times
3. Eventually it will start interacting with the chat menu bar

`[SEVERE] Menu item doesn't exist - [Switch tab, Public: Show autochat, Public: Show standard, Public: Show friends, Public: Show none, Public: Hide, Public: Clear history, Filter public chat, Setup your autochat, Cancel]`

The code used:
```
Item food = getfoodmethod(); //Using stream.name(food_name)
        if(!food.valid()) {
            return;
        }

        if(food.interact(Config.food.action))
        {
            [redacted]
        }
```

**Expected behavior**
The character interacts with the inventory

**Emulator or device**
 - Device/Emulator: [Bluestacks]
 - OS: [Android Pie]
 - Arch: [ARM64]

**Comment by TacticalMullet** [comment]
+1 I have been seeing this as well. For me, it seems like something happens on script start that caches the inventory location incorrectly. It always breaks at the beginning of running a script, never halfway through for me.

**Comment by rvbiljouw** [comment]
made some adjustments to cache time in latest build - we believe this is a result of "performance enhancements" and will look for a better way to do it but feedback on whether the issue is at least somewhat reduced would be helpful

**Comment by Nickert1337** [comment]
Haven't been able to test yet, but I will probably test it tomorrow and let you know.

**Comment by constt** [comment]
@Nickert1337 pleaswe test
