### ISSUE TITLE
[BUG] Grand Exchange Buying Items

### ISSUE THREAD

**Issue by 7upSprite** [powbot/issues#76]
I get everything in the logger, but it won't type the string. Then it continues to loop endlessly.

if (gpInventoryCount > 5000000 && GrandExchange.opened()) {
            System.out.println("Buying bond now");
            GrandExchangeItem bond = GrandExchangeItem.Companion.fromName("Old school bond");
            GrandExchange.createOffer(bond, 1, bond.getHigh(), true);
            System.out.println("Created offer");
            Condition.wait(()-> gpInventoryCount < 5000000, 250, 60);
            return getLoopReturn();
        }

[] Buying bond now
[INFO] Received expected action - WidgetActionEvent(widgetId=30474244, interaction=Back, name=, id=1)
[] Created offer

![ecVoI0Fcbx](https://user-images.githubusercontent.com/48745305/188530366-4c691da4-b86f-4528-a069-9719b978b29f.gif)

I was following the docs examples:

![image](https://user-images.githubusercontent.com/48745305/188530629-fdb5e785-8b76-466d-98d1-c6d6bf2cac05.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: [Android Pie] - Default
 - Arch: [e.g. ARM64] - Default

**Comment by rvbiljouw** [comment]
this should be fixed in the latest build

**Comment by 7upSprite** [comment]
Tested on new client build released today 9/9/22

Using the same code as above, it does not click on the Create Offer button, it just stays on the main screen shown in the picture. 

Also, previously I received the following error logs: 
"[] Buying bond now
[INFO] Received expected action - WidgetActionEvent(widgetId=30474244, interaction=Back, name=, id=1)
[] Created offer"

However today I am not receiving the [INFO] line, I am only receiving the other 2 lines. Shown below
[] Buying bond now
[] Created offer
[] Buying bond now
[] Created offer

![image](https://user-images.githubusercontent.com/48745305/189293551-bed38a57-aff6-4823-b5e8-27b7ea0cf080.png)

**Comment by constt** [comment]
@7upSprite please try now, widgets were broken before

**Comment by 7upSprite** [comment]
@constt 

https://imgur.com/a/cx4RNAU

[INFO] Got TouchEvent(type=Press, mod=0, x=539, y=226, isScriptInput=true, consumed=false, unscaled=Point(x=965, y=404)) (3
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=539, y=226, isScriptInput=true, consumed=false, unscaled=Point(x=965, y=404))
[INFO] Got TouchEvent(type=Release, mod=0, x=539, y=226, isScriptInput=true, consumed=false, unscaled=Point(x=965, y=404)) (3
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=539, y=226, isScriptInput=true, consumed=false, unscaled=Point(x=965, y=404))
[INFO] trying to click menu itemorg.powbot.api.rt4.Menu$TextFilter@d114daf
[INFO] found menu item at 1
[INFO] Got TouchEvent(type=Press, mod=0, x=638, y=158, isScriptInput=true, consumed=false, unscaled=Point(x=1142, y=283)) (250
[WARNING] Received unexpected event while waiting for TouchEvent(type=Press, mod=0, x=893, y=261, isScriptInput=true, consumed=false, unscaled=Point(x=893, y=261)) - TouchEvent(type=Press, mod=0, x=638, y=158, isScriptInput=true, consumed=false, unscaled=Point(x=1142, y=283)) 
[INFO] Got TouchEvent(type=Release, mod=0, x=627, y=151, isScriptInput=true, consumed=false, unscaled=Point(x=1122, y=270)) (229
[WARNING] Received unexpected event while waiting for TouchEvent(type=Release, mod=0, x=893, y=261, isScriptInput=true, consumed=false, unscaled=Point(x=893, y=261)) - TouchEvent(type=Release, mod=0, x=627, y=151, isScriptInput=true, consumed=false, unscaled=Point(x=1122, y=270)) 
[INFO] Received expected action - NpcActionEvent(name=Grand Exchange Clerk, id=3109, level=-1, interaction=Exchange)
[] Buying bond now
[INFO] Got TouchEvent(type=Press, mod=0, x=168, y=305, isScriptInput=true, consumed=false, unscaled=Point(x=301, y=546)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=168, y=305, isScriptInput=true, consumed=false, unscaled=Point(x=301, y=546))
[INFO] Got TouchEvent(type=Release, mod=0, x=168, y=305, isScriptInput=true, consumed=false, unscaled=Point(x=301, y=546)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=168, y=305, isScriptInput=true, consumed=false, unscaled=Point(x=301, y=546))
[INFO] Got TouchEvent(type=Press, mod=0, x=42, y=51, isScriptInput=true, consumed=false, unscaled=Point(x=75, y=91)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=42, y=51, isScriptInput=true, consumed=false, unscaled=Point(x=75, y=91))
[INFO] Got TouchEvent(type=Release, mod=0, x=42, y=51, isScriptInput=true, consumed=false, unscaled=Point(x=75, y=91)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=42, y=51, isScriptInput=true, consumed=false, unscaled=Point(x=75, y=91))
[INFO] Received expected action - WidgetActionEvent(widgetId=10616882, interaction=Select, name=Old school bond, id=1)
[INFO] Got TouchEvent(type=Press, mod=0, x=511, y=357, isScriptInput=true, consumed=false, unscaled=Point(x=915, y=639)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=511, y=357, isScriptInput=true, consumed=false, unscaled=Point(x=915, y=639))
[INFO] Got TouchEvent(type=Release, mod=0, x=511, y=357, isScriptInput=true, consumed=false, unscaled=Point(x=915, y=639)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=511, y=357, isScriptInput=true, consumed=false, unscaled=Point(x=915, y=639))
[INFO] Got TouchEvent(type=Press, mod=0, x=170, y=434, isScriptInput=true, consumed=false, unscaled=Point(x=304, y=777)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=170, y=434, isScriptInput=true, consumed=false, unscaled=Point(x=304, y=777))
[INFO] Got TouchEvent(type=Release, mod=0, x=170, y=434, isScriptInput=true, consumed=false, unscaled=Point(x=304, y=777)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=170, y=434, isScriptInput=true, consumed=false, unscaled=Point(x=304, y=777))
[INFO] Received expected action - WidgetActionEvent(widgetId=30474244, interaction=Back, name=, id=1)
[] Created offer

**Comment by 7upSprite** [comment]
Imgur link has video of what it's currently doing. I believe it's not hitting enter/submitting the inputted price

**Comment by 7upSprite** [comment]
I manually changed to single-tap mode in my client, and also changed to dev mode. Not sure which fixed it, but it is working since switching to those 2 variables.

**Comment by 7upSprite** [comment]
@constt 

Issue is hit or miss. I included logs and a gif of whats happening. After it puts the price of item in, it doesn't submit the offer.

![GxQyDZEy2u](https://user-images.githubusercontent.com/48745305/191167533-82e4ce1c-d27e-40d3-8c91-6fd917a2f875.gif)


[INFO] Received expected action - WidgetActionEvent(widgetId=10616882, interaction=Select, name=Hammer, id=1)
[INFO] Got TouchEvent(type=Press, mod=0, x=492, y=359, isScriptInput=true, consumed=false, unscaled=Point(x=881, y=642)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=492, y=359, isScriptInput=true, consumed=false, unscaled=Point(x=881, y=642))
[INFO] Got TouchEvent(type=Release, mod=0, x=492, y=359, isScriptInput=true, consumed=false, unscaled=Point(x=881, y=642)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=492, y=359, isScriptInput=true, consumed=false, unscaled=Point(x=881, y=642))
[INFO] Got TouchEvent(type=Press, mod=0, x=170, y=434, isScriptInput=true, consumed=false, unscaled=Point(x=304, y=777)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=170, y=434, isScriptInput=true, consumed=false, unscaled=Point(x=304, y=777))
[INFO] Got TouchEvent(type=Release, mod=0, x=170, y=434, isScriptInput=true, consumed=false, unscaled=Point(x=304, y=777)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=170, y=434, isScriptInput=true, consumed=false, unscaled=Point(x=304, y=777))
[INFO] Received expected action - WidgetActionEvent(widgetId=30474244, interaction=Back, name=, id=1)
[INFO] Got TouchEvent(type=Press, mod=0, x=168, y=305, isScriptInput=true, consumed=false, unscaled=Point(x=301, y=546)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=168, y=305, isScriptInput=true, consumed=false, unscaled=Point(x=301, y=546))
[INFO] Got TouchEvent(type=Release, mod=0, x=168, y=305, isScriptInput=true, consumed=false, unscaled=Point(x=301, y=546)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=168, y=305, isScriptInput=true, consumed=false, unscaled=Point(x=301, y=546))
[INFO] Got TouchEvent(type=Press, mod=0, x=200, y=107, isScriptInput=true, consumed=false, unscaled=Point(x=358, y=191)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=200, y=107, isScriptInput=true, consumed=false, unscaled=Point(x=358, y=191))
[INFO] Got TouchEvent(type=Release, mod=0, x=200, y=107, isScriptInput=true, consumed=false, unscaled=Point(x=358, y=191)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=200, y=107, isScriptInput=true, consumed=false, unscaled=Point(x=358, y=191))
[INFO] Received expected action - WidgetActionEvent(widgetId=10616882, interaction=Select, name=Hammer, id=1)
[INFO] Got TouchEvent(type=Press, mod=0, x=504, y=361, isScriptInput=true, consumed=false, unscaled=Point(x=902, y=646)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=504, y=361, isScriptInput=true, consumed=false, unscaled=Point(x=902, y=646))
[INFO] Got TouchEvent(type=Release, mod=0, x=504, y=361, isScriptInput=true, consumed=false, unscaled=Point(x=902, y=646)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=504, y=361, isScriptInput=true, consumed=false, unscaled=Point(x=902, y=646))
[INFO] Got TouchEvent(type=Press, mod=0, x=166, y=433, isScriptInput=true, consumed=false, unscaled=Point(x=297, y=775)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=166, y=433, isScriptInput=true, consumed=false, unscaled=Point(x=297, y=775))
[INFO] Got TouchEvent(type=Release, mod=0, x=166, y=433, isScriptInput=true, consumed=false, unscaled=Point(x=297, y=775)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=166, y=433, isScriptInput=true, consumed=false, unscaled=Point(x=297, y=775))
[INFO] Received expected action - WidgetActionEvent(widgetId=30474244, interaction=Back, name=, id=1)
[INFO] Got TouchEvent(type=Press, mod=0, x=172, y=288, isScriptInput=true, consumed=false, unscaled=Point(x=308, y=515)) (0
[INFO] Received expected touch - TouchEvent(type=Press, mod=0, x=172, y=288, isScriptInput=true, consumed=false, unscaled=Point(x=308, y=515))
[INFO] Got TouchEvent(type=Release, mod=0, x=172, y=288, isScriptInput=true, consumed=false, unscaled=Point(x=308, y=515)) (0
[INFO] Received expected touch - TouchEvent(type=Release, mod=0, x=172, y=288, isScriptInput=true, consumed=false, unscaled=Point(x=308, y=515))

**Comment by constt** [comment]
@7upSprite please try in 20mins on development

**Comment by 7upSprite** [comment]
@constt GE Buying is confirmed working, thank you. I am able to buy multiple different items without fail. Tomorrow I will do an extensive test on more GE stuff (primarily Selling because I havent touched that yet, and will update this issue accordingly if I find anything)

**Comment by iDznPB** [comment]
Closing as confirmed fixed with no further updates
