### ISSUE TITLE
[BUG] World.getType() returns UNKNOWN

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#77]
**Describe the bug**
Worlds are returning UNKNOWN type rather than their appropriate types when using Worlds.current()

**To Reproduce/Line of code causing issue**

```
System.out.println(Worlds.current().getType());
```

**Expected behavior**
It should return the current world with the type FREE, MEMBERS, DEADMAN, or PVP

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: 64 bit

**Comment by constt** [comment]
@5Henveru2 Which world? Looking at the client state debug which shows curr world this is fine

**Comment by 5Henveru2** [comment]
W369 is an example
![image](https://user-images.githubusercontent.com/96345909/188655268-8e81b74c-04ca-48eb-a527-662269069f64.png)

**Comment by constt** [comment]
@5Henveru2 Just tested and works fine right now on that world, is this a consistent issue?

**Comment by 5Henveru2** [comment]
@constt It is still occurring quite often for me.  It fails to pull world info for the current world using Worlds.current(), and the debug shows as above.  It gets the number correct but nothing else.  Just tested to confirm

**Comment by constt** [comment]
@5Henveru2 It's likely an issue with your connection/proxy, that information is fetched from our API.

**Comment by 5Henveru2** [comment]
I'm not using any proxies, is there any info I can grab to help debug this?

**Comment by constt** [comment]
@5Henveru2 I made a change which may help

**Comment by iDznPB** [comment]
@5Henveru2 are you able to test this?

**Comment by 5Henveru2** [comment]
Seems to be resolved
