### ISSUE TITLE
[BUG] `interact(f() -> MenuCommand)` always returns true

### ISSUE THREAD

**Issue by TacticalMullet** [powbot/issues#78]
**Describe the bug**
when calling `interact(f() -> MenuCommand)`, `true` is returned even if it missclicks. (works correctly for `interact(action: String)`)

**To Reproduce/Line of code causing issue**
```
fun main() {
    Debugger().startScript(useDefaultConfigs = false)
}

@ScriptManifest(
    name = "Debugger",
    description = "Debugger",
)
class Debugger : AbstractScript() {
    override fun poll() {
        Thread.sleep(500)
        log.info { "running" }
        val entityName = "Rough wall"
        val entity = Objects.stream().name(entityName).nearest().first()
        val action = "Climb"

        entity.interact { it.option.startsWith(entityName) && it.action == action }
            .also { log.info { it.toString() } }

        Thread.sleep(5000)
    }
}
```

**Expected behavior**
`interact(f() -> MenuCommand)` should return false when it misses the object or fails to locate the MenuCommand matching the predicate.

**Logs**
```
message: "Success, loaded Debugger from bytes with new configs!"
[INFO] running
[INFO] true           // missed, clicked on ground
[INFO] running
[SEVERE] Menu item doesn't exist - [Walk here, Examine Table, Cancel]            // missed, clicked on table
[INFO] true
```

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by rvbiljouw** [comment]
this should be fixed in the latest build

**Comment by TacticalMullet** [comment]
> this should be fixed in the latest build

Latest build in the downloads channel is from Sept 2, is there a more recent build available?

**Comment by TacticalMullet** [comment]
reinstalled & tested, confirmed working. thanks!!!
