### ISSUE TITLE
[BUG]Widget boundingRects randomly invalid

### ISSUE THREAD

**Issue by Nickert1337** [powbot/issues#80]
**Describe the bug**
OelRunedoku is heavily based on widgets and components. To solve the sudoku I'm reading the components and clicking other components to finalize the board.

When trying to interact with the components to place the runes it sometimes gives a invalid boundingRect, which causes .click() to missclick. As an example I added a paint to the runedoku script:

![image](https://user-images.githubusercontent.com/98966743/188883860-b7257942-ad27-40cc-be29-6217deac48ef.png)

The red square is the position the bot thinks the component should be at and the green square is where the calculated position should be at (by using the X,Y of the rune in the board)

If I click on the green square using Input.Tap the script succesfully completes the sudoku, this means the components are clicked in the right manner. If component.click() is used, the whole board is scrambled.

I've also see boundingrect return invalid values (above 30.000 for example). 

**To Reproduce/Line of code causing issue**
1. Start OelRunedoku
2. See shit go haywire

```
Point targetPosition = new Point(250 + (tile.x * 36), 183+ (tile.y * 32));
Point targetPoint = tileComponent.boundingRect().center();

if(Math.abs(targetPosition.getX() - targetPoint.getX()) > 36 || Math.abs(targetPosition.getY() - targetPoint.getY()) > 32) {
                        System.out.println("Found invalid placement");
                        Condition.sleep(5000);
                    }
                    
                    
                    tileComponent.click(); //clicks at random positions
                        Input.tap(targetPosition); //clicks at the correct position
```

**Expected behavior**

**Emulator or device (please complete the following information):**
 - Device/Emulator: [Bluestacks]
 - OS: [Android Pie]
 - Arch: [ARM64]

**Comment by constt** [comment]
@Nickert1337 should be fixed

**Comment by Nickert1337** [comment]
I'm on holiday for the week and expect to be back around 18 sept. Would be great if someone else could test, otherwise we'll have to wait till I'm back.
