### ISSUE TITLE
Players API returning non-existing objects [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#81]
**Describe the bug**
Players API returns phantom objects.

**To Reproduce/Line of code causing issue**
``` Players.stream().at(Players.local().tile()).filtered { it != Players.local() }.count())```
Returns 1, when it should be 0

If I remove the local player check:
```Players.stream().at(Players.local().tile()).count())```
It will report 2.

Name and model of the phantom player object is empty/null

**Screenshots**
![image](https://user-images.githubusercontent.com/64224090/189478157-964b822c-d22a-4b9a-9781-492a176533d7.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: ALL
 - OS: Android 9/12
 - Arch: ARM64

**Comment by constt** [comment]
@Protoprize try now please

**Comment by ghost** [comment]
@constt  partially fixed. No phantom players now. 
Getting an issue now where the local player has two different addresses. Tried with following code:

```
.addString("Phantom player address :") { Players.stream().at(Players.local().tile()).filter { it != Players.local() }.first().address().toString()}
.addString("Local player address :") { Players.local().address().toString()}
```


Both are the local player if checked by name + other details. Just different addresses are shown for both, presumably meaning the .filter check will return the localplayer no matter what


![image](https://user-images.githubusercontent.com/64224090/189521220-fabec169-3352-43d1-aa65-cbdfb95b909e.png)

![image](https://user-images.githubusercontent.com/64224090/189521324-5a930851-f490-4e40-a93c-3d96308e9a13.png)

**Comment by constt** [comment]
@Protoprize please try in 20

**Comment by ghost** [comment]
Fixed :D
