### ISSUE TITLE
[BUG] Movement.destination() multiplier is off

### ISSUE THREAD

**Issue by Krulvis** [powbot/issues#87]
**Describe the bug**
Movement.destination() multiplier is wrong

**To Reproduce/Line of code causing issue**
print out:
```
Movement.destination()
```

**Expected behavior**
Movement.destination returns a sensible tile

**logs**
`destination=Tile(x=877136816, y=6872, floor=1, localX=877133448, localY=3368)`

**Comment by constt** [comment]
@Krulvis Looks like our hook for that is broken, spent a few hours trying to find it and couldn't

For now i've made the movement api set destination after it tries to walk to a tile, not perfect but should make most scripts work for now.

**Comment by constt** [comment]
This has been fixed
