### ISSUE TITLE
[BUG] GroundItem.valid() returns false

### ISSUE THREAD

**Issue by Krulvis** [powbot/issues#89]
**Describe the bug**
Any GroundItem.valid() false when it is still existing on the ground.

**To Reproduce/Line of code causing issue**

```
GroundItems.stream().name("Some item you dropped").first().valid()
```

**Expected behavior**
GroundItem.valid() returns true when the item exists

**Comment by constt** [comment]
@Krulvis unable to reproduce this, where are you trying?

**Comment by Krulvis** [comment]
2nd floor of morytania slayer tower

**Comment by iDznPB** [comment]
Likely similar issue as before @constt when items on the floor for rooftops weren't valid either, ground floor works fine which is probably why you can't replicate it

**Comment by constt** [comment]
@iDznPB you've been able to replicate?

**Comment by iDznPB** [comment]
Not recently, will check tomorrow

**Comment by iDznPB** [comment]
Tested every floor of the slayer tower, items are returning fine and valid() is true
@Krulvis @constt 
Happy to close?

**Comment by constt** [comment]
Thanks @iDznPB
