### ISSUE TITLE
[BUG] GroundItem.interact() does nothing

### ISSUE THREAD

**Issue by Krulvis** [powbot/issues#91]
**Describe the bug**
GroundItem.interact(action, name) does nothing

**To Reproduce/Line of code causing issue**
```
val gi = GroundItems.stream().name("Some grounditem").nearest().first()
gi.interact("Take") OR gi.interact("Take", "Some grounditem")
```

**Expected behavior**
Client interacts with grounditem

**Comment by Krulvis** [comment]
This is due to https://github.com/powbot/issues/issues/89 if Interactive.interact() still checks for `valid()`

**Comment by constt** [comment]
Going to close and resolve in #89
