### ISSUE TITLE
Inventory positions are broken [BUG]

### ISSUE THREAD

**Issue by ghost** [powbot/issues#93]
**Describe the bug**
Inventory position is broken and showing in the wrong location.

**Screenshots**

![image](https://user-images.githubusercontent.com/64224090/190994757-8af55b7c-d45f-4751-bcb7-ba1b84c57949.png)

**Comment by constt** [comment]
@Protoprize this still happen since latest updates?

**Comment by iDznPB** [comment]
Confirmed working
