### ISSUE TITLE
[BUG] Inventory.get() includes empty inventory spaces as items

### ISSUE THREAD

**Issue by 5Henveru2** [powbot/issues#94]
**Describe the bug**
Title should suffice, the empty inventory interfaces are being included as items

**Expected behavior**
Empty inventory spaces should not be returned in Inventory.get()

**Screenshots**(https://cdn.discordapp.com/attachments/930269678767575080/1021569720996073602/unknown.png)

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: ARM64

**Comment by constt** [comment]
Should be fixed in next

**Comment by iDznPB** [comment]
@5Henveru2 can you check and confirm if resolved please?

**Comment by iDznPB** [comment]
Tested this myself and seems to be resolved now.
