### ISSUE TITLE
[BUG] `Inventory.stream().name(<String>)` is unreliable

### ISSUE THREAD

**Issue by TacticalMullet** [powbot/issues#95]
**Describe the bug**
`Inventory.stream().name(<String>)` occasionally returns 0 entries when the inventory does in fact contain the thing. 
Happens while inventory is open.
It only happens intermittently, I have scripts that routinely check for certain items in the inventory and this happens within about 5 minutes or less. 

**To Reproduce/Line of code causing issue**
It is intermittent, but, here's the code to reproduce - with a Hammer in inventory,

```
Game.tab(Game.Tab.INVENTORY)
println(Inventory.stream().name("Hammer").count().toString())
```

**Expected behavior**
Stream correct inventory items

**Emulator or device (please complete the following information):**
 - Device/Emulator: Bluestacks
 - OS: Android Pie
 - Arch: e.g. ARM64

**Comment by constt** [comment]
@TacticalMullet You should change your code to:

if (Game.tab(Game.Tab.INVENTORY)) { 
...

**Comment by TacticalMullet** [comment]
thanks, I will add some checks around whether the inv is actually open and reopen this if i have any more issues. 🙏
