### ISSUE TITLE
[BUG] Item not found in Inventory

### ISSUE THREAD

**Issue by 7upSprite** [powbot/issues#99]
**Describe the bug**
The item shown in the screenshot which has the name "Dwarf remains" is not showing in the inventory explorer and I am unable to interact with the item. 

The following picture shows the item in my inventory:

![image](https://user-images.githubusercontent.com/48745305/191389932-dc05f045-9c30-4dc6-b767-efe962c3e8dd.png)

![image](https://user-images.githubusercontent.com/48745305/191389963-d75f4b89-0a38-41a6-9151-74b905d5985f.png)

Item dwarfRemainsInventory = Inventory.stream().name("Dwarf remains").first();
if (dwarfRemainsInventory.valid()) {
log.info("in my inventory");
return 100;
}

The above code always returns false even though the remains are in my inventory.

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: Default
 - Arch: Default

**Comment by 5Henveru2** [comment]
It is item id 0 if that helps @constt, pretty sure we had an issue handled for this with old client

**Comment by constt** [comment]
@7upSprite try in 20mins
